### ISSUE TITLE
Add operations endpoints

### ISSUE THREAD

**Issue by clouserw** [mozilla/universal-search#1]
The operations infrastructure is expecting some endpoints for each project to reply in a standardized fashion.  This will be expected for all Test Pilot experiments as well as Test Pilot itself.  They are handy for debugging too!
1. Respond to /**version** with a [JSON version object](https://docs.google.com/document/d/1rGVyiLYvZyKE2oHcSVx-vBmQRKhs1kLLgn7xeCs6qKs/edit)
2. Respond to /**heartbeat** with a HTTP 200 or 5xx on error
   
   this endpoint is used by external monitoring to check the health of the service
   it is recommended to check the app's dependencies (database, caches, etc) here
3. Respond to /**lbheartbeat** with an HTTP 200
   
   used by the load balancer to check if the server and application is OK
   do not include dependency checks as this check may trigger automatic node termination and replacement

**Comment by chuckharmston** [comment]
Moved to https://github.com/mozilla/universal-search-recommendation/issues/34
