### ISSUE TITLE
Prepare for acceptance test

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#105]
- [x] Get Universal Search added to Test Pilot.
  - [x] Copy needed
  - [x] Screenshots needed
  - [x] Hosting/signing story needed (#24)
- ~~Add onboarding experience.~~
  - ~~Mocks needed.~~
- [x] Recommendation server deployment
  - [x] Add staging server to options in add-on
- [x] Pre-cache searches for "space deb" and "f"

**Comment by jaredhirsch** [comment]
@chuckharmston Are you actively working on this issue? I suspect waffle may have put it in progress when it's not.

**Comment by chuckharmston** [comment]
This was actually finished for today's acceptance test; I didn't get a chance to move it out. Good catch.
