### ISSUE TITLE
Always hide the highlight when the popup first opens

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#118]
@chuckharmston raised this concern in the pull request that removed highlighting from the recommendation:

> I'm not sure the UX here is right; if we're going to prevent the top result from being highlighted by default if it's a recommendation, it seems like we should never highlight the top result. It's very disorienting to be typing and have the highlight flash in while typing a string: https://chchc.ch/PgsBdx

@nchapman / @bryanbell, thoughts?

I don't see a lot of options here:
- We could leave it like it is.
- We could try to strip the highlight out of the 'heuristic' ("search with...") top result. I'm not sure how much work that would be, probably a 'medium' 2-3 day bug.
- Note that it would be hard to remove the top 'heuristic' result completely, that's not an option here.

**Comment by chuckharmston** [comment]
We could also revert to the previous behavior of having the recommendation be highlighted, right?

**Comment by jaredhirsch** [comment]
@chuckharmston Actually, the previous behavior was broken: when you started typing, the recommendation was highlighted, but if you immediately hit Enter, you wouldn't be taken to the recommendation URL. You'd be taken to the URL/search page for whatever you had typed in the urlbar.

With the old system, the only way to surf to the recommendation URL would be to down arrow past it, then up arrow back to it, which would fill the urlbar with the recommendation URL, and _then_ hit Enter. It looked better, but the interaction was broken.

The basic principle is that the highlight should tell you what's about to happen when you hit Enter. Another basic assumption is that we don't want to interfere with the user typing something and hitting Enter without interacting with the popup in any way: that means we can't just auto-send them to the recommendation URL if they type a few chars, then hit Enter.

**Comment by chuckharmston** [comment]
I vote for any option that maintains consistency for queries that do and do not have recommendations available. I guess that, in this case, that means that we should not highlight anything until the user interacts with it.

**Comment by nchapman** [comment]
Yes I think we should hide the highlight so that it's consistent with the experience when there is a recommendation.

**Comment by jaredhirsch** [comment]
Looks like our highlight stealing code does not work any more. FF 45.0.2, Mac.

Going to dig into why it's broken tomorrow.

**Comment by jaredhirsch** [comment]
The duplicate checking code broke highlight management. With that change backed out, I'm able to consistently remove the highlight (with some exceptions, filed as separate sub-bugs).

Should have a PR out soon.
