### ISSUE TITLE
handle duplicates between recommendation and rich list / urlbar autocomplete

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#12]
I think we need some input from product here. Is the best thing to just not show the recommendation, if it duplicates one of the top 5 results (hence, is already visible in the popup)?

**Comment by jaredhirsch** [comment]
@bryanbell @nchapman Any thoughts on how best to handle duplication between the recommendation and one or more of the first page of results?

**Comment by nchapman** [comment]
Since the primary purpose of the recommendations is to help users visit new sites/content, we ideally wouldn't get in the way of navigating to sites they've already visited. I think we should hide our recommendation if there's already a matching site in the frecent results. This will prevent us from doing annoying things like showing you a reddit.com recommendation when you're trying to get to your favorite subreddit for example.

**Comment by jaredhirsch** [comment]
@nchapman Sounds good! I'm thinking we should only compare with the initial page of results shown in the popup (the top 5), since few people scroll and the recommendation could provide value in that case. Thoughts?

**Comment by nchapman** [comment]
@6a68 cool idea! Let's try it that way!

**Comment by jaredhirsch** [comment]
:beers: Thanks Nick

**Comment by jaredhirsch** [comment]
This is mostly done, WIP branch is here: https://github.com/6a68/universal-search/commit/c82c11b

**Comment by jaredhirsch** [comment]
It looks like this change broke highlight management. At least, that's how it looks to me. @chuckharmston Have you noticed that highlight stealing has gotten super buggy since this landed?

**Comment by chuckharmston** [comment]
I didn't notice anything while testing this PR, but I've largely been working on the server since then, haven't been using a build with this change in it.

**Comment by jaredhirsch** [comment]
I'm not sure what happened: at the time, it seemed like this was working flawlessly. Need to investigate a little bit more.

**Comment by jaredhirsch** [comment]
Discussed with Nick on IRC. Removing the public launch blocking tag; we'll see if people notice / complain.

**Comment by jaredhirsch** [comment]
Summary of the state of this bug so far:

Background:
- We can't detect when results are ready until they are rendered in the DOM.
- We can poll the C++ search service controller for results while it's still searching, but once it sends results to the UI, the controller nulls out its copy of the results.
- We render our recommendation independently of when results are rendered.

Approaches to handling dupes:
- If we render the recommendation before the results, then discover the recommendation is a dupe, then removing it will cause visual jank. Since the height of the awesomebar is variable in the new style (currently in dev edition), the height of the whole popup jumps, which is even more noticeable.
- We could wait to render the recommendation until we're sure it's not a dupe. Need to carefully measure how this impacts performance.
