### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by ghost** [mozilla/universal-search#120]
We talked about this in a meeting, but I forget which one.

Now that we have stage, we should run a load tester on it to get a rough idea of what kind of performance we can expect.  Even if it's just returning nulls from memcache, it would be helpful to get a rough idea of requests/sec.  

Ideally testing this won't cost us a fortune in API queries. :)

**Comment by chuckharmston** [comment]
I don't think we should consider this until we have some sort of upstream cache; either Varnish-like or a CDN.

We could avoid costing us money in API queries by disallowing outbound HTTP requests from the worker server. All the jobs would fail, but as far as load testing the application server, it should be fine (still 1 memcached read per request).

**Comment by jaredhirsch** [comment]
Moved to https://github.com/mozilla/universal-search-recommendation/issues/88 with the other server bugs.
