### ISSUE TITLE
Update recommendation image display logic

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#121]
The way recommendations are currently displayed, there is one awful UI problem: a website's logo and favicon are often shown adjacently, and they are often similar or identical. This leads to weird experiences like this:

![image 2016-03-30 at 10 15 58 am](https://cloud.githubusercontent.com/assets/23885/14153736/496ab4b6-f676-11e5-9c21-605c3e5f0ac1.png)![image 2016-03-30 at 10 15 37 am](https://cloud.githubusercontent.com/assets/23885/14153737/496ae5a8-f676-11e5-87a3-f4f9c689c99e.png)

_(Recommendation to follow)._

**Comment by chuckharmston** [comment]
After talking with Bryan, I've come up with a proposal for how we might fix this. We have two slots where we can place images, always showing one of them, but at least two of them:

![slots](https://cloud.githubusercontent.com/assets/23885/14153796/8e387e02-f676-11e5-8f52-65698b5d641f.png)

The small slot is 16x16, the large one is 32x32. We also have three image data points:
- A key image ([example](https://static01.nyt.com/images/2016/03/22/nyregion/00water-slide-PROMO/00water-slide-PROMO-facebookJumbo-v7.jpg)), of variable size.
- A logo ([example](https://logo.clearbit.com/nytimes.com?size=64)), 64x64.
- A favicon ([example](https://static01.nyt.com/favicon.ico)), of variable size, sometimes only 16x16.

I propose the following heuristic to determine how we use these images. This always prioritizes the best data; we always show the key image if available, and always shows the logo if available. We no longer use the letterbox at all.
- If we have a key image and logo, put the former in the large slot and the latter in the small slot: ![keyimage logo](https://cloud.githubusercontent.com/assets/23885/14153938/47899bc0-f677-11e5-9bec-4f847ba38c84.png)
- If we have a key image and favicon, put the former in the large slot and the latter in the small slot: ![keyimage favicon](https://cloud.githubusercontent.com/assets/23885/14154034/b8598770-f677-11e5-8e6d-e5519ba94471.png)
- If we have a key image with no logo or favicon, put the former in the large slot and nothing in the small slot: ![keyimage](https://cloud.githubusercontent.com/assets/23885/14154248/ac6b62fc-f678-11e5-9d75-53129156ba32.png)
- If we have no key image but a logo, put the logo in the big slot and nothing in the small slot: ![logo favicon](https://cloud.githubusercontent.com/assets/23885/14154277/c9c1e47a-f678-11e5-9df0-7f811d58eebd.png)
- If we have no key image or logo but do have a favicon, put the favicon in the small slot and nothing in the large slot. Adjust the spacing so the top of the small slot is aligned with the top of the text. ![favicon](https://cloud.githubusercontent.com/assets/23885/14154393/72f99416-f679-11e5-9a83-178b834bfe3a.png)
- If we have no images, put the generic favicon in the small slot and nothing in the large slot. Adjust the spacing so the top of the small slot is aligned with the top of the text. ![no images](https://cloud.githubusercontent.com/assets/23885/14154435/a8c91a94-f679-11e5-82e2-ab67fe00475f.png)

Thoughts? @nchapman @clouserw @bryanbell @6a68

**Comment by chuckharmston** [comment]
Since we're breaking the grid set by the other recommendations, we'd probably want a rule between our recommendation and the result of the results (which was in the original mocks anyway).

**Comment by nchapman** [comment]
@chuckharmston the rules sound good to me! I notice that this proposes that we overlap the icons instead of having them in two columns. I'd love to see a mockup of how this will look in the current awesome bar UI. @bryanbell could you provide that?

**Comment by jaredhirsch** [comment]
I suspect the overlapping images might be too visually dense to be effective in an ephemeral interface. It's hard to scan/parse borderless, overlapping images.

The rules also seem somewhat complex for a throwaway prototype. What if we just do a better job of picking a single best image?

**Comment by chuckharmston** [comment]
> I notice that this proposes that we overlap the icons instead of having them in two columns. I'd love to see a mockup of how this will look in the current awesome bar UI.

That came from Bryan, but it's probably just easier to do in code. I'll try to throw that together.

> The rules also seem somewhat complex for a throwaway prototype. What if we just do a better job of picking a single best image?

I think it seems more complex than it is since I spelled out every permutation for clarity. It really comes down to:
1. Never put the logo next to the favicon
2. Use the best images available.

**Comment by jaredhirsch** [comment]
OK, taking a step back:

Our current goal is to determine if server-generated recommendations improve engagement with the urlbar popup.

We switched to a XUL prototype to minimize UI differences between the recommendation and existing results, so that changes in engagement could be attributed to the quality of the recommendation data. This proposal seems to be leading us in the opposite direction.

(If the current goal hasn't changed, it makes sense to remove the large image and 'recommended' text: these elements visually distinguish the recommendation result from the other results, when our goal is to eliminate UI variables. I'm happy to file bugs for these tasks, and we can discuss them in the next planning meeting, or whenever we run out of issues in the current milestone.)

For now, I'd suggest that we could collect UI experiment ideas in the search roadmap, and we could discuss the roadmap in planning.

**Comment by chuckharmston** [comment]
Jared's point is well-taken, and I'd love to hear what @nchapman has to say about that.

Some promised screenshots, in a few configurations. Worth noting: the key image from Embedly for some sites—Facebook included—is basically a larger version of the favicon, so the proposal above only partially solves the problem.

<img width="695" alt="both" src="https://cloud.githubusercontent.com/assets/23885/14165227/cc0b60d0-f6c3-11e5-9702-d0a696d81f47.png">
<img width="728" alt="logo" src="https://cloud.githubusercontent.com/assets/23885/14165229/ce3437a6-f6c3-11e5-978d-9dc1535324e5.png">
<img width="680" alt="favicon" src="https://cloud.githubusercontent.com/assets/23885/14165230/d032635c-f6c3-11e5-8d3d-f604a7b0e9bc.png">

**Comment by bryanbell** [comment]
> We switched to a XUL prototype to minimize UI differences between the recommendation and existing results...

I wouldn't say that his was the driving rationale at all. There was no real consideration, at least on my part, of fitting the look on the injected suggestion in with the standard content for scientific reasons. I was only done that way out of a misunderstanding of what was possible to show. 

After doing more work on these types of icon+image in Activity stream did I recognize the limitation. Which is that many sites are only going to have one thing to show. Our UI assumed 2 different things would be common, it's not. More often than not we are showing 2 of the same images next to each other. 

The trouble we have now, with repeating icons, is that we are showing content that doesn't fit in with the existing content. It's standing out in an awkward way that draws even more attention to itself.

**Comment by nchapman** [comment]
> We switched to a XUL prototype to minimize UI differences between the recommendation and existing results

The primary goal was to avoid changes to the existing results and not so much the UI of the recommendation result itself. It's important for people to understand that it's a new kind of result, and we've already visually distinguished it in various ways: large image, dividing line, "recommended" label etc.

This seems to me to be a fairly pragmatic change to avoid some of the most popular sites looking silly by showing duplicated icons. While the stacked style is a bit more visually dense, I feel like it still conveys the most important information clearly enough. I think the examples that @chuckharmston showed above look great, and we should go with that.

**Comment by jaredhirsch** [comment]
Thanks for clarifying, all. Sounds like we'll probably add this to the upcoming 4/22 milestone.

**Comment by chuckharmston** [comment]
With more rigid result types (#165), this no longer applies.
