### ISSUE TITLE
Send correct headers for CDN caching

### ISSUE THREAD

**Issue by ghost** [mozilla/universal-search#123]
Any CDN or proxy we end up with will respect the standard caching headers, so we should make sure we are sending them.  

This can be a no-cache header for empty results and a cache for 24 hours header for results with stuff in them or whatever.  cache-control, expires, etags, pragma, etc.  whatever you kids are using these days.

:rotating_light:

**Comment by chuckharmston** [comment]
Moved to https://github.com/mozilla/universal-search-recommendation/issues/85
