### ISSUE TITLE
Integration with Servo?

### ISSUE THREAD

**Issue by paulrouget** [mozilla/universal-search#125]
I don't know if that makes sense, but could we eventually re-use within Servo? That means no XUL, just pure HTML.

**Comment by paulrouget** [comment]
(and no chrome privileges)

**Comment by jaredhirsch** [comment]
Hi Paul,

I think it's technically possible for a web interface to be reused within Servo, but note that the current prototype doesn't use HTML. The roadmap for this experiment changed in Q1, and this new prototype makes minimal UI changes, and uses XUL, not HTML. We're waiting on a roadmap for Q2-Q3, which might involve enough visual experimentation to justify reintroducing an iframe-based interface.

As for what would be required to connect Servo to an iframe-based bit of UI, the older prototype uses WebChannel for communication between the iframe and the add-on. If Servo supports something similar, that is, two-way JSON messaging between privileged and unprivileged code, then an HTML interface should work just fine.

The deprecated HTML interface repos are here: [iframe](https://github.com/mozilla/universal-search-content), [add-on](https://github.com/mozilla/universal-search-addon).

Ping me on IRC (_6a68) if you want to chat about experimenting with HTML UI in Servo, I may be able to find a little time to play around. For now, closing this bug. :beers:
