### ISSUE TITLE
Add Universal Search icon for about:addons page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#130]
The "Test Pilot" add-on has a nice icon, it may be nice to add one for Universal Search as well. Not sure if we want to recycle the search icon SVG that we're using elsewhere. /cc @johngruen 

<img width="930" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/14295789/eb4a09f8-fb2b-11e5-8da0-f2974da5013d.png">

**Comment by jaredhirsch** [comment]
@johngruen Are we just doing a magnifying glass icon for this add-on for public launch? If so, I guess we can close this bug?
