### ISSUE TITLE
Add "available on Test Pilot" badge to README?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#139]
We should maybe add <img src="https://img.shields.io/badge/available_on-Test_Pilot-0996F8.svg"> to the README. It's a very pretty badge.

Not sure if we want to link it to testpilot PROD, or if we can link to inner pages (ie: if we link directly to http://testpilot.dev.mozaws.net/experiments/universal-search but aren't logged in, will it correctly redirect you back to that page after you finish the auth loop).

**Comment by jaredhirsch** [comment]
PRs welcome :-)
