### ISSUE TITLE
init xhr connection early

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#14]
prewarm the http/2 connection by firing a dummy xhr at the rec server a few seconds after the window loads

**Comment by chuckharmston** [comment]
This is a great idea. On urlbar focus?

**Comment by jaredhirsch** [comment]
it's a bit challenging to decide how long to wait, because there's _so much code_ that is synchronously initialized in gecko - probably will be best to ask adw or Mossop

**Comment by jaredhirsch** [comment]
It looks like our code doesn't run until the popup is opened for the first time, so the earliest we could do this would probably be the recommendation-server's init method?
