### ISSUE TITLE
Odd favicon behavior when typing domains like "spotify"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#141]
I installed the add-on via Test Pilot and noticed that when typing a URL like "spotify", the background colors change from red, and blue, and the actual favicon, then back to a color, then back to a favicon.

Seems a bit jumpy.

![spotify](https://cloud.githubusercontent.com/assets/557895/14578106/27467f9e-0334-11e6-8d07-a92414ed70bd.gif)

**Comment by jaredhirsch** [comment]
Thanks for filing this bug. Closing in favor of #121, which updates the image layout and removes the random-colored 'letterbox'.
