### ISSUE TITLE
Uninstalling throws errors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#145]
Some probably useless debug information from Test Pilot Browser Console output.

Basically I just enabled and disabled the Universal Search experiment:

![firefox_test_pilot_-_universal_search_and_browser_console_and_1__docker-compose_up__docker-compose_](https://cloud.githubusercontent.com/assets/557895/14658286/7cfd9ed4-0647-11e6-88b9-9c8ebd3f02ec.png)

Trying to find the source of the error, but having problems resolving **chrome://universalsearch-lib/content/universal-search.js:237**.

Closest I can find is [./lib/universal-search.js:237](https://github.com/mozilla/universal-search/blob/9de3974ec1e390df543b532ad0e9d55da9b0aa01/lib/universal-search.js#L237), which is a semi-unhelpful:

``` js
  onError: function(msg) {
    console.error(msg);
  }
```

---

> 1461106471486 addons.xpi  WARN    Exception running bootstrap method shutdown on universal-search@mozilla.com: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIXPCComponents_Utils.unload]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/pdehaan/dev/tmp/ff-tool/_temp/profiles/fftool.s92U7w/extensions/universal-search@mozilla.com.xpi!/bootstrap.js :: shutdown :: line 34"  data: no] Stack trace: shutdown()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/pdehaan/dev/tmp/ff-tool/_temp/profiles/fftool.s92U7w/extensions/universal-search@mozilla.com.xpi!/bootstrap.js:34 < this.XPIProvider.callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4657 < this.XPIProvider.uninstallAddon()@resource://gre/modules/addons/XPIProvider.jsm:4921 < AddonWrapper.prototype.uninstall()@resource://gre/modules/addons/XPIProvider.jsm:7129 < uninstallExperiment/<()@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-addon/index.js:349 < safeCall()@resource://gre/modules/AddonManager.jsm:179 < makeSafe/<()@resource://gre/modules/AddonManager.jsm:195 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746

**Comment by jaredhirsch** [comment]
Thanks for filing this, @pdehaan! I bet the problem is that `console` isn't globally visible to that code--it'd need to be something like `this.win.console`.

**Comment by jaredhirsch** [comment]
Sizing as small, assuming the problem really is calling `console.error` rather than `this.win.console.error`.
