### ISSUE TITLE
Final Assets

### ISSUE THREAD

**Issue by johngruen** [mozilla/universal-search#147]
[Here's spreadsheet for Test Pilot assets](https://docs.google.com/a/mozilla.com/spreadsheets/d/170wRKBJ6LV67wIwAm8flkyYaweYNejuuiZU6tENgbcg/edit?usp=sharing). Please add links/copy/etc. I'll be tracking this bug and pestering @nchapman and @bryanbell

**Comment by jaredhirsch** [comment]
Seems related to #130
