### ISSUE TITLE
Recommendation should say Yahoo

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#151]
The recommendation needs to carry Yahoo branding, part of the terms of using their search API.

**Comment by jaredhirsch** [comment]
@nchapman As a first approximation, can we just change the text from `Recommended` to `Recommendations by Yahoo!`?

**Comment by nchapman** [comment]
Talked to Brian Smith, and we don't need to include attribution unless Yahoo requests it. So we're clear to move ahead without attribution for now.

**Comment by nchapman** [comment]
In case this does come up again, these are the attribution guidelines: https://developer.yahoo.com/attribution/
