### ISSUE TITLE
Relevance?

### ISSUE THREAD

**Issue by Verdi** [mozilla/universal-search#159]
This is my first universal search result. It looks like a poorly targeted ad.
![prince](https://cloud.githubusercontent.com/assets/107992/14918364/1dcd9578-0de9-11e6-8ee8-b815bb54e92e.png)

**Comment by jaredhirsch** [comment]
Hi @Verdi,

Thanks for trying out the search add-on, and thanks for the feedback.

We're going to be doing a lot of work in the next couple of weeks to initially restrict results to just Wikipedia pages and the most popular top-level domains. After that, we'll bring in specific types of recommendations, like weather or movie data. Our goal is to provide a great experience, and as you've discovered, we're not quite there yet.

In case you're interested, the product roadmap is linked from this project's wiki page: https://wiki.mozilla.org/Test_Pilot/Universal_Search

Closing this bug, but if you'd like to discuss further, you're welcome to join us in IRC (#testpilot) or on the Test Pilot mailing list, see the main Test Pilot wiki page for details: https://wiki.mozilla.org/Test_Pilot
