### ISSUE TITLE
allow the popup to be pinned open

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#16]
Basically, we need a slightly fancier version of this one-liner:

``` js
gURLBar.popup.addEventListener('popuphiding', (e) => { e.preventDefault(); })
```

We'll need to:
- check some global app state to decide whether to pin the popup open
- not use an anonymous function, so the listener can be detached

**Comment by chuckharmston** [comment]
Can we set this as addon config?

**Comment by jaredhirsch** [comment]
it'd be a bit awkward, because the popup is pinned open per-window. enabling it in addon config would lead to a bunch of odd windows stuck open, and it might even be hard to resize the window enough to get access to the config screen to disable it ;-)

**Comment by jaredhirsch** [comment]
hmm, maybe we could do a 'debug' config setting that displays a menu button that lets you pin/unpin the popup for a given window? that might be nice

**Comment by chuckharmston** [comment]
We could always allow a pinned window to be closable through a button added in debug mode, a key sequence (`<esc> <esc>`), or something along those lines.

**Comment by jaredhirsch** [comment]
:+1: all great ideas

However this gets implemented, we should also document the existence of the option in the README.
