### ISSUE TITLE
Add-on updates are not working

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#168]
Debugging the auto-update process can be fiddly; `update.rdf` has to be served with the right mime type.

Let's make sure the update process works before public launch.

**Comment by jaredhirsch** [comment]
Verifying updates work is pretty easy:
1. manually install an older version of the add-on (test pilot doesn't need to be involved)
2. Go into about:addons, into the gear menu, and 'check for updates'
3. add-on should be bumped up to the latest version

**Comment by jaredhirsch** [comment]
Hmm, updates don't seem to be working, but I'm not sure why. The update.rdf file is being served with the correct mime type, and the link looks correct in install.rdf. To be continued.

**Comment by chuckharmston** [comment]
When trying to manually force updates, the browser does see the new version number:

![screen shot 2016-05-03 at 1 58 34 pm](https://cloud.githubusercontent.com/assets/23885/14996631/2a766e2e-1138-11e6-85d9-2107c2732777.png)

But it reports as `plain` even though it returned `Content-Type:"application/rdf+xml"`. That's curious. The request Firefox fires off has `Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"`, so I tried updating the `Content-Type` of `update.rdf` to `application/xml`. It did not help.

**Comment by chuckharmston** [comment]
Manually triggering an update check, for posterity:

``` javascript
Cu.import("resource://gre/modules/AddonManager.jsm");

let updateListener = {
  onCompatibilityUpdateAvailable: (addon) => {
    console.log('compatability update available', addon);
  },
  onNoCompatibilityUpdateAvailable: (addon) => {
    console.log('no compatability update available', addon);
  },
  onUpdateAvailable: (addon, install) => {
    console.log('update available', addon, install);
  },
  onNoUpdateAvailable: (addon) => {
    console.log('no update available', addon);
  },
  onUpdateFinished: (addon, error) => {
    console.log('update finished', addon, error);
  }
};

AddonManager.getAddonByID('universal-search@mozilla.com', (addon) => {
  addon.findUpdates(updateListener, AddonManager.UPDATE_WHEN_USER_REQUESTED);
});
```
