### ISSUE TITLE
No recommendations after I type a period in address bar

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#170]
Found in 1.0.2, but this seems to be a one-time thing.

---
### Steps to reproduce:
1. Install latest Universal Search via Test Pilot (prod).
2. Open the Browser Console (Tools > Web Developer > Browser Console).
3. Slowly type the following domains "motorola.com", "mozilla.com", "mozilla.org"
### Actual results:

| MESSAGE | FILE |
| --- | --: |
| No recommendation available for "motor". | recommendation-server.js:89 |
| No recommendation available for "motoro". | recommendation-server.js:89 |
| No recommendation available for "motorol". | recommendation-server.js:89 |
| No recommendation available for "motorola". | recommendation-server.js:89 |
| No recommendation available for "motorola.". | recommendation-server.js:89 |
| No recommendation available for "motorola.c". | recommendation-server.js:89 |
| No recommendation available for "motorola.co". | recommendation-server.js:89 |
| No recommendation available for "motorola.com". | recommendation-server.js:89 |
| No recommendation available for "mozilla.c". | recommendation-server.js:89 |
| No recommendation available for "mozilla.co". | recommendation-server.js:89 |
| No recommendation available for "mozilla.com". | recommendation-server.js:89 |
| No recommendation available for "mozilla.or". | recommendation-server.js:89 |
| No recommendation available for "mozilla.org". | recommendation-server.js:89 |

Typically as soon as i type "." in a domain name, I stop getting suggestions. Although it seems like the algorithm is learning and it makes it hard to reproduce since now I'm getting suggestions for those two domains.

**Comment by chuckharmston** [comment]
"No recommendation available" means that the server did not have a recommendation generated for that search yet. It's good and expected, since it takes time to generate these recommendations, and it'd be a very jarring experience to have one show up a second after the rest of the popup has resolved.

We also don't show recommendations if we think you are typing a URL, to avoid privacy leakage.
