### ISSUE TITLE
TelemetryStopwatch: requesting elapsed time for nonexisting stopwatch

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#171]
Found in 1.0.2 (although not sure if this is specific to Universal Search).

---
### Steps to reproduce:
1. Install latest universal search add-on via TestPilot (prod).
2. Go to a site.
3. Open the Browser console (Tools > Web Developer > Browser Console).
4. Click the dropdown icon in the address bar (I'm using Developer Edition).
### Actual results:

![show_history_and_download_firefox_ _free_web_browser_ _mozilla_and_universal-search_metrics_md_at_master_ _mozilla_universal-search_ _github](https://cloud.githubusercontent.com/assets/557895/14968530/1a17edf8-1072-11e6-83bc-0a945a103e1d.png)

> _TelemetryStopwatch: requesting elapsed time for nonexisting stopwatch. Histogram: "PLACES_AUTOCOMPLETE_6_FIRST_RESULTS_TIME_MS", key: "null"_

<img width="1117" alt="browser_console_and_issues_ _mozilla_universal-search" src="https://cloud.githubusercontent.com/assets/557895/14968499/f49ca780-1071-11e6-8b90-36f4a53de10a.png">

**Comment by chuckharmston** [comment]
CCing @6a68 here in case he knows something I don't, but I'm pretty sure this is entirely unrelated to us. Perhaps worth a Bugzilla bug on [Firefox::Search](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Search)?

Thanks for the report!
