### ISSUE TITLE
misalignment of suggestion with the rest of the results in Nightly 48

### ISSUE THREAD

**Issue by ckarlof** [mozilla/universal-search#173]
<img width="910" alt="screenshot 2016-05-02 17 44 38" src="https://cloud.githubusercontent.com/assets/2365255/14972104/ccce4558-108d-11e6-8083-eed08497cac8.png">

**Comment by chuckharmston** [comment]
Thanks for the report, Chris!

Dev and Nightly currently have a patch that changes the design of the awesomebar popup. We haven't quite gotten around to updating to match yet, but it [is on our radar](https://github.com/mozilla/universal-search/issues/98).
