### ISSUE TITLE
Add reference to testpilot.firefox.com in addon meta

### ISSUE THREAD

**Issue by ckprice** [mozilla/universal-search#174]
We have to add something to the `about:addons` page that 
1. Links back to https://testpilot.firefox.com.
2. Identifies this a Test Pilot experiment.

Exact specifications provided by @nchapman, @johngruen

**Comment by jaredhirsch** [comment]
This is a really easy fix. We just need some text to insert in the description in [`install.rdf`](https://github.com/mozilla/universal-search/blob/master/install.rdf#L10).

**Comment by nchapman** [comment]
Let's add this text to the bottom of the description:

> Learn more about this Test Pilot experiment at https://testpilot.firefox.com/

**Comment by jaredhirsch** [comment]
The description has to be text. If you are ok with a non-linkified URL, this can work. Otherwise there's [`homepageURL`](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#homepageURL) which is designed to display the add-on homepage in the about:addons UI.

**Comment by jaredhirsch** [comment]
@nchapman See my comment above

**Comment by jaredhirsch** [comment]
Nick's comments from IRC:

```
12:36 PM <nchapman> hiya
12:36 PM <nchapman> so we have to say it’s test pilot
12:36 PM <nchapman> and we have to have the link
12:37 PM <nchapman> it being clickable is an optimization :)
```
