### ISSUE TITLE
Results are mis-aligned

### ISSUE THREAD

**Issue by ghost** [mozilla/universal-search#175]
When I do a search with a result, the results look misaligned to me.  I was expecting to see the small icon lined up with the favicons of all the other sites, but they aren't.

It's not off by much normally, but when using Tab Center it's emphasized, especially if Tab Center is pinned open.  I'm going to file a bug for Tab Center because I don't think the awesomebar should cover the tabs when it opens, but I also wanted to file this because I think the alignment is wrong even without Tab Center installed.

Screenshot to show misalignment:

![alignment](https://cloud.githubusercontent.com/assets/16946141/14992816/b7d9e938-111c-11e6-8d99-37d58377833c.png)

**Comment by chuckharmston** [comment]
This is because Dev and Nightly currently have a patch that changes the design of the awesomebar popup. We haven't quite gotten around to updating to match yet, but it [is on our radar](https://github.com/mozilla/universal-search/issues/98); it was just deemed not to be part of launch scope..
