### ISSUE TITLE
client-side metrics

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#18]
use nsIObserver idea-town metrics signals to end serialized objects over

**Comment by jaredhirsch** [comment]
Google doc with draft of metrics we'd gather: https://docs.google.com/document/d/1-FeQS1bMAT1S9MfPB6sm6czsRXdNf3OI3PTUw3JHU18/edit

**Comment by jaredhirsch** [comment]
Setting the label to 'medium' means that we should aggressively timebox the initial pass at metrics, just reporting the absolute minimum. If there's time, we can report additional details.

**Comment by clouserw** [comment]
Should have something for this soon.

See also https://github.com/mozilla/universal-search-recommendation/issues/35

**Comment by chuckharmston** [comment]
I'll work on defining this, but implementation is blocked on mozilla/testpilot#234.
