### ISSUE TITLE
Sometimes get the wrong results when I backspace

### ISSUE THREAD

**Issue by ghost** [mozilla/universal-search#181]
This isn't 100% reproducible, but I tried it on a brand new profile (see recording below) and got it on the second try.

STR:
1) Type 'fac' to get facebook to prefill
2) Backspace over everything and type 'h'
3) See Facebook recommended

![out-12](https://cloud.githubusercontent.com/assets/16946141/15001411/1ac2f088-114c-11e6-9745-f6aec3f450f7.gif)

(edit: lol @ gif quality.  What are you kids using for web animations these days? webm?)

**Comment by jaredhirsch** [comment]
Marking as public launch blocking just so we all notice it this week.

**Comment by chuckharmston** [comment]
I have not been able to reproduce this at all.

@wresuolc Can I ship you a fancy special build with additional logging output?

**Comment by ghost** [comment]
sure

**Comment by chuckharmston** [comment]
@wresuolc added a debugging build here: https://gist.github.com/chuckharmston/e4e2c51ac031eb80f6194735a1814683#debugging-build

I'm particularly interested in any logs surrounding a failed recommendation. It's pretty noisy; filtering for `universal-search` will help you make sense of it:

![screen shot 2016-05-04 at 11 26 27 am](https://cloud.githubusercontent.com/assets/23885/15022894/10559192-11eb-11e6-96c3-d7ebe26b5f3d.png)

**Comment by ghost** [comment]
I installed the build in a new profile.  On a fresh restart the awesomebar works once and I see a suggestion for facebook, and then when I backspace I see this in the console (among lots of other things):

```
JavaScript error: chrome://browser/content/urlbarBindings.xml, line 1446: TypeError: this.searchSuggestionsNotification is null
JavaScript error: chrome://universalsearch-ui/content/recommendation-row.js, line 259: TypeError: can't convert null to object
JavaScript error: chrome://browser/content/urlbarBindings.xml, line 1446: TypeError: this.searchSuggestionsNotification is null
JavaScript error: chrome://browser/content/urlbarBindings.xml, line 1446: TypeError: this.searchSuggestionsNotification is null
```

and the last line just repeats forever and the awesomebar stops working completely.

**Comment by chuckharmston** [comment]
> JavaScript error: chrome://universalsearch-ui/content/recommendation-row.js, line 259: TypeError: can't convert null to object

This is the one that I needed. Thanks! Fix will be incoming.
