### ISSUE TITLE
Wrong title color

### ISSUE THREAD

**Issue by ghost** [mozilla/universal-search#182]
Chuck asked for an issue about our title color on Linux.  It should be white?  Filing so we don't lose track -- we can triage later. :)

**Comment by chuckharmston** [comment]
<img width="662" alt="screen shot 2016-05-04 at 8 49 03 am" src="https://cloud.githubusercontent.com/assets/23885/15017997/16f5e9cc-11d5-11e6-9118-97727e2908e7.png">

This was what prompted me to ask for this (thanks, @wresuolc!); there should be a title above the Facebook URL in our recommendation with the words "Facebook – Log In or Sign Up". It appears that we never specified an appropriate font color for it.

**Comment by chuckharmston** [comment]
Hm, this should be fine.

@clouserw distro/version?

**Comment by ghost** [comment]
Ubuntu with their default dark-ish theme.  Nightly firefox

**Comment by chuckharmston** [comment]
It looks like Ubuntu no longer uses the prefixed `-moz-MenuText` constant, instead rolling with the unprefixed `MenuText`. Should be an easy fix.
