### ISSUE TITLE
experiment info page shows image with a (misleading) omnibar

### ISSUE THREAD

**Issue by gregglind** [mozilla/universal-search#192]
at:  https://testpilot.firefox.com/experiments/universal-search it shows a single omnibar style thingy. 

Am I supposed to get that?  I still have navbox and searchbox.

**Comment by jaredhirsch** [comment]
@gregglind The Tab Center addon breaks Customize mode, which might be preventing this addon from adjusting the address and search bars.

This addon, on its own, will remove the search bar if present, and restore the search bar on disable/uninstall.
