### ISSUE TITLE
Update metrics format to use snake_case

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#193]
Looks like we're using snake_case for the keys sent over by the server. Let's update the keys sent over by JS to match.

**Comment by jaredhirsch** [comment]
Hmm, the redshift schema bug is already filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1270586

Maybe we just leave things as they currently are, for now?

**Comment by ghost** [comment]
if you want to change the schema, update that bug asap

**Comment by chuckharmston** [comment]
Closing; doesn't seem worth the discarding of data it would require.
