### ISSUE TITLE
Can't tab out of search box

### ISSUE THREAD

**Issue by jbuck** [mozilla/universal-search#194]
When I have Universal Search enabled I cannot use the Tab key to tab into web content

**Comment by jaredhirsch** [comment]
@jbuck thanks for the bug report!

If the user hits Tab while the popup is closed, we should hand that key off to the Gecko keypress handler.

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
