### ISSUE TITLE
Ensure all interactions work if UnifiedComplete is disabled

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#20]
I'm not sure what happens if the Unified Complete pref is disabled (`browser.urlbar.unifiedcomplete`).

Look at dxr / try disabling it, and make sure the recommendations work smoothly.

**Comment by chuckharmston** [comment]
This is odd. It's more acceptance criteria than task. I guess we label it like this?

**Comment by nchapman** [comment]
I just tested it, and it does continue to work when `browser.urlbar.unifiedcomplete` is false (wow). It looks like it was [set to true by default in 43](https://wiki.mozilla.org/QA/Places/Unified_autocomplete#Enabling_the_component). I don't think we actually need/want to support the disabled unified complete case. It's great that it works, but I don't think it's something we need to monitor and test in an ongoing way.

**Comment by jaredhirsch** [comment]
You make solid points, @nchapman. Closing :-)
