### ISSUE TITLE
Restore user's search suggestions preference on uninstall

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#202]
Currently, we enable search suggestions when the add-on is installed:

https://github.com/mozilla/universal-search/blob/master/bootstrap.js#L14-L17

On uninstall, we clear the pref, restoring it to its default state:

https://github.com/mozilla/universal-search/blob/master/bootstrap.js#L28-L30

We could instead save the user's preference and restore it on uninstall. We do something similar for hiding and restoring the search bar (see universal-search.js), so it seems like we should be able to use the same approach.

**Comment by jaredhirsch** [comment]
@chuckharmston pointed out that this was discussed before: https://github.com/mozilla/universal-search/pull/49#discussion_r54509619

I'm not sure what data storage is available to us from the bootstrap.js context, but, worst case, we should be able to pass some info to the universal-search.js script via the `UniversalSearch.load` call.

**Comment by davidhedlund** [comment]
[mylabel:bug](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Abug%22+in%3Acomments&type=Issues&ref=searchresults)
