### ISSUE TITLE
Incorporation of the hidden search filters - Universal search bar

### ISSUE THREAD

**Issue by Noitidart** [mozilla/universal-search#203]
I was wondering if anyone had any creative ideas on how to make the hidden feature of filters more visible:

https://github.com/Noitidart/AwesomeBar-Power-Tip/issues/4

[Mozilla Support :: Awesome Bar - Changing results on the fly](https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs?redirectlocale=en-US&redirectslug=awesome-bar-find-your-bookmarks-history-and-tabs#w_changing-results-on-the-fly)

This user had an idea similar to how the current search bar does it:

https://github.com/Noitidart/AwesomeBar-Power-Tip/issues/4

![](https://cloud.githubusercontent.com/assets/3525376/10223484/f3511e64-687a-11e5-9c05-d7689ed24cce.png)

I made a simple addon like this - https://addons.mozilla.org/en-US/firefox/addon/awesomebar-power-tip/

**Comment by jaredhirsch** [comment]
@Noitidart Again, you have some really cool ideas for updating the awesomebar UI. I'd suggest you chat with adw or mak in #fx-team sometime, or file a bug (Firefox :: Location Bar) with your suggestions. For now, closing this one here :-)

**Comment by Noitidart** [comment]
Thanks! Will try chat with them. Just brainstorming but it would be awesome if it lead to some elegant solutions! :)
