### ISSUE TITLE
Incorporate the simple search engine selection with tab (no keywords)

### ISSUE THREAD

**Issue by Noitidart** [mozilla/universal-search#204]
Keywords are not so popular by most users. That's why I think these hidden filters never got popular - https://github.com/mozilla/universal-search/issues/203

The search engine bar we have right now is awesome. By pressing tab or shift tab. Maybe we can use the left/right arrow keys we can easily pick the engine. The up/down arrow keys move through the suggestions:

![](http://i.imgur.com/F9UTnD8.png)

I was wondering if there were any ideas on incorporating this? Like at the bottom of the awesome bar?

**Comment by Aurizen** [comment]
As a user I find it very important the image above is. I use multiple search engines like the one above. I use wikia sites based on video games and TV shows. incorporating Noitidart's idea would be great.

**Comment by jaredhirsch** [comment]
@Noitidart @Aurizen Thanks for the feedback and suggestions. This add-on is an experiment in delivering server-generated recommendations, and not an experiment in how the awesomebar UI is presented, so we likely won't be exploring these ideas any time soon. Feel free to file a bug against the Firefox component / Location Bar product in Bugzilla, if you'd like to send this suggestion to the desktop team that hacks on the production awesomebar.

**Comment by Noitidart** [comment]
Ah drats. Makes sense though its different things. Thanks for the share 6a68 :)
