### ISSUE TITLE
Simple numerical calculations/results should be presented better

### ISSUE THREAD

**Issue by bull500** [mozilla/universal-search#207]
The current format for simple calculation is a bit confusing.
There's multiple results and search suggestions

![screenshot from 2016-05-11 21-11-35](https://cloud.githubusercontent.com/assets/8917275/15187023/04a9499c-17bd-11e6-9619-64693376755f.png)

**Comment by jaredhirsch** [comment]
@bull500 Thanks for the bug report. The search suggestions shown in your screenshot aren't touched by this add-on. You would see the same search suggestions without this add-on installed. Closing.
