### ISSUE TITLE
Weather info should be provided within the Universal Search Bar

### ISSUE THREAD

**Issue by bull500** [mozilla/universal-search#208]
Currently it just suggests a search suggestion.  
Would be beautiful and apt if it could display the result right away, with or without the icons etc. - just the right info

**Comment by jaredhirsch** [comment]
This is in the [roadmap](https://trello.com/c/uEiLk9mJ/9-i-want-weather-recommendations-that-include-current-temperature-and-a-multiday-forecast-so-that-i-can-quickly-learn-the-weather-), great suggestion!
