### ISSUE TITLE
Specific search queries should be made to return specific answers instead of websites

### ISSUE THREAD

**Issue by bull500** [mozilla/universal-search#209]
If I enter a query such as "burj Khalifa height" it would be nice to see the result within the search bar instead of performing a complete search or being suggested to a visit a wiki/official site.

**Comment by jaredhirsch** [comment]
@bull500 Thanks for the suggestion!

We used to return arbitrary search results, but scaled back to just wikipedia and top-level domains for now. The rationale is that general search quality is a very difficult problem to solve, so we're going to focus on good quality for specific, narrowly-defined recommendation types, and gradually add other types. If you peek at our [product roadmap](https://trello.com/b/ojJPAvsU/universal-search), you'll see that movie, weather, and recipe suggestions are some of the types we hope to add soon.

Thanks for the feedback, and stay tuned for updates :-)

**Comment by jaredhirsch** [comment]
Oh, I don't know if I was quite clear enough in my response: we'd like to do things like show you a weather forecast in the recommendation UI, or show you a link to buy tickets for a local showing of a movie--so your suggestion of providing instant answers (to borrow a phrase from DDG) is definitely something we hope to explore in the future.

**Comment by bull500** [comment]
Hey @6a68  
Thank you for taking my views into account. 
Sorry for the excess bugs i filed. I didn't understand that they fall under the same category!
Anyway look forward to this! Thanks for the Roadmap link as well! :)
