### ISSUE TITLE
Enable Circle-CI

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#21]

**Comment by jaredhirsch** [comment]
@chuckharmston why not a good first bug?

**Comment by chuckharmston** [comment]
We have no tests or place to put a built addon yet.

**Comment by jaredhirsch** [comment]
@chuckharmston Hmm, good point. We don't have many good first bugs, I'd like to find a way to modify this one to make it more beginner friendly. Any ideas?

How about this: Travis-CI calls the makefile to build the add-on, and verifies that the add-on was created?

**Comment by jaredhirsch** [comment]
We did something along these lines for the old add-on: https://github.com/mozilla/universal-search-addon/blob/master/.travis.yml

**Comment by chuckharmston** [comment]
Sure! Could also coordinate with the test pilot team to work out the process to get it hosted on production.
