### ISSUE TITLE
Various buttons in *content* don't work when Universal Search is enabled (or newly disabled)

### ISSUE THREAD

**Issue by birtles** [mozilla/universal-search#213]
STR:
1. Enable Universal Search
2. Go to a file on GitHub where you have commit access.
3. Click the pencil icon to edit the file.

Expected results:
Something happens -- i.e. the file preview becomes an editable textarea.

Actual results:
Nothing

I've experience the same thing when looking at Bugzilla search results. Click the "Change Columns" link at the bottom and on the next page the "Change Columns" button doesn't do anything.

My colleague was able to reproduce this as well. We are both on Windows.

Furthermore, disabling Universal Search does not fix it until you restart the browser.

**Comment by birtles** [comment]
I should also add that it appears various buttons in the Firefox hamburger menu don't work while Universal Search is enabled. However, I was surprised that even content is affected by this.

Note that I am running with e10s disabled.

**Comment by jaredhirsch** [comment]
@birtles Hi, thanks for the bug report. I can't reproduce this issue using the steps you've listed, and I don't see how the search add-on could have caused these symptoms, as the only part of the UI it modifies is the awesomebar. That said, XBL is involved, so anything's possible `¯\_(ツ)_/¯`

Can you please tell me what other TxP experiments you had installed at the time, any other add-ons, what OS, and what version of Firefox?

**Comment by birtles** [comment]
Hi! Yes, of course:
TxP: Universal Search and Activity Center
OS: Windows 10 (Japanese)
Firefox: Nightly, e10s disabled
Add-ons: LastPass, ADB Helper, FoxClocks, Markdown Viewer, Mozilla Tree Status, Restartless Restart, Rikaichan, Strict Pop-up blocker (disabled), User Agent Overrider

As mentioned, my colleague was able to reproduce immediately. He is also on Windows 10 (Japanese), using Firefox Nightly and I suspect has e10s disabled.

Another colleague didn't try but also reported that the buttons in the hamburger menu are unresponsive for him when trying Universal Search.

I don't know if either of them also had Activity Center running at the same time.

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
