### ISSUE TITLE
Restore the search box when disabling

### ISSUE THREAD

**Issue by birtles** [mozilla/universal-search#214]
When disabling Universal Search, the separate search box is not restored. I need to go to Customize and re-add it manually. This is true even after restarting.

**Comment by jaredhirsch** [comment]
@birtles do you also have tab center installed?

**Comment by jaredhirsch** [comment]
Closing as a duplicate of #216. @birtles, please feel free to reopen if you feel this was duped in error.

**Comment by birtles** [comment]
No, I don't although I did enable it previously.
