### ISSUE TITLE
highlight color conflicts with text color on Windows 7

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/universal-search#215]
_filing on behalf of @jmathies_

awesome hover highlight color conflicts with test color of suggested entry.

windows 7
![highlight](https://cloud.githubusercontent.com/assets/959837/15214969/ad5a0592-1815-11e6-9808-f6d8676093be.jpg)

_moved from https://github.com/mozilla/testpilot/issues/806_

**Comment by chuckharmston** [comment]
Thanks for the report, @jmathies!

It looks like you're using either Developer Edition or Nightly. Those release branches currently have an in-progress restyle going on that we're waiting to stabilize before tackling. You can track that here: https://github.com/mozilla/universal-search/issues/98
