### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#217]
Bug filers aren't leaving actionable information in their bug reports. Update contributing.md to ask that they list OS, Firefox version, all other add-ons installed, and any errors seen in the browser console.

**Comment by chuckharmston** [comment]
We could use issue templates for it? That's more visible.

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by comoss** [comment]
Can I claim this? I'd be happy to make an issue template asking users to list the requested information.
