### ISSUE TITLE
feature request: gif search

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/universal-search#218]
Would be cool to be able to search gifs from the address bar and quickly copy url to clipboard.

I'm sure @johngruen could come up with a cool UI.
What I'm picturing is starting a search with something like:
1. `gif<tab>`
2. address bar adjusts to: `gif: <your search query>`
3. as you type gifs slide into the result box.
4. From here you can `<tab>` to each one making the preview slightly larger, with a transparent overlay of `<enter> to add to clipboard`.

http://api.giphy.com/

**Comment by jaredhirsch** [comment]
Cool idea! This would be tough to implement using the current XUL-based approach. The preview image size is currently too small to show a comprehensible GIF. Giphy's API is public-only, and not recommended for production deployments--but there might be a way to tweak the yahoo search API to retrieve animated images. Setting needs:product to get some additional input.
