### ISSUE TITLE
muiltible pages open

### ISSUE THREAD

**Issue by shilow19** [mozilla/universal-search#224]
i am using windows 10 os and  Firefox 46.0.1
![2016-05-14](https://cloud.githubusercontent.com/assets/19353672/15270966/adc44f78-1a00-11e6-991c-88a7ebc76f87.png)
![2016-05-14 1](https://cloud.githubusercontent.com/assets/19353672/15270968/b4904dfc-1a00-11e6-8fd5-a0095a2bf1ad.png)

   when i find a page i want to be on it will load fine after a few min the page will do 1 of 2 thing reload or universal search web page will open any were from 1 to 3 web search pages at a time.it will also if playing a game stop the game like its set to pause.then when i went to submit the report on what i though about the add-on i could not send the submission also i use a dell i have a 1 button push to take screenshots when using this i had to use the ctrl and screenshot at the same time i did not know at the time i had to use both keys to do the screenshots i tried to do a screenshot of the web pages reloading and or opening new search pages but had to figure out how to get my screenshots working plus test pilot icon will not stay on in the menu bar but here are the screenshots of not being able to send in report and universal was still in use from what i was showen it did not look like it added on

**Comment by chuckharmston** [comment]
Thanks for the report!

The feedback process is managed by Test Pilot, so I've moved the issue over there: https://github.com/mozilla/testpilot/issues/856
