### ISSUE TITLE
Will not enable

### ISSUE THREAD

**Issue by Tyman691** [mozilla/universal-search#227]
My Firefox Info
Ver:  46.0.1
![universal search](https://cloud.githubusercontent.com/assets/19416409/15337428/f1262432-1c38-11e6-9fe4-29f545537bb4.JPG)

Universal Search will not enable.
Clicked "enable universal search button", button changed to say "enabling." Button stuck on "enabling"
Screen shot attached.

**Comment by chuckharmston** [comment]
Thanks for the report!

I believe this is a dupe of a Test Pilot issue that we are tracking here: https://github.com/mozilla/testpilot/issues/802
