### ISSUE TITLE
Search Box missing on browser restart

### ISSUE THREAD

**Issue by HarshSharma12** [mozilla/universal-search#228]
On enabling universal search, the search box gets removed from layout. It is available in the customize menu but on adding it back the changes persist only till all the windows of the browser are closed. 

Every time the browser restarts, it has to be added again.

**Comment by jaredhirsch** [comment]
@HarshSharma12 Sounds like expected behavior: the Universal Search add-on does remove the separate search bar. You'll have to uninstall Universal Search to bring the search bar back. Closing, but feel free to comment or reopen if something else is up.

**Comment by HarshSharma12** [comment]
I get that it is the expected behavior to remove the search box when you enable the universal search but aftre enabling if I readd the search box shouldn't it stay there. Right now I have to add it every time.
