### ISSUE TITLE
Add a Makefile to build the addon

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#23]
zip the addon files into an .xpi

**Comment by chuckharmston** [comment]
If you don't mind waiting until tomorrow morning, I'll take this.

**Comment by jaredhirsch** [comment]
Sure! I think we'll want to manually bump the version numbers in install.rdf and update.rdf, then pass the new version to make on the command line. We could use xml parsing to programmatically get at those rdf files, but it seems like a lot of code, while a few lines of release process docs should get the job done just as well.

Based on a conversation w/@lmorchard, it sounds like the testpilot site will handle the jpm sign & push to S3 steps for us, so this should be a pretty simple task.
