### ISSUE TITLE
Awesome bar suggestions are broken after some

### ISSUE THREAD

**Issue by lissyx** [mozilla/universal-search#231]
STR:
1. Enabled all test pilot addons (TabCenter, Universal Search, Activity Stream)
2. After some hours/days of use, CTRL+T then start typing a previously visited URL

Expected:
 Awesome bar suggestions are shown

Actual:
 Content is empty.

This is with nightly (https://hg.mozilla.org/mozilla-central/rev/c4449eab07d39e20ea315603f1b1863eeed7dcfe) on ubuntu 15.10. Restarting Firefox bypasses the issue.

Content of the JS Console:
loadIntoWindow startuniversal-search.js:47
loadIntoWindow finishuniversal-search.js:59
grammalecte-fr:Unable to add directory: home/alex/.mozilla/firefox/yakxclvy.default/extensions/French-GC@grammalecte.net/data/dictionaries/spellchecker.js:103
grammalecte-fr:"
undefined
NS_ERROR_FILE_UNRECOGNIZED_PATH
line: 99
Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath]
--- Stack ---
addDirectory@resource://gre/modules/commonjs/toolkit/loader.js -> resource://french-gc-at-grammalecte-dot-net/spellchecker.js:99:20
addExtensionDictFolder/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://french-gc-at-grammalecte-dot-net/spellchecker.js:131:4
safeCall@resource://gre/modules/AddonManager.jsm:179:5
makeSafe/<@resource://gre/modules/AddonManager.jsm:195:25
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:779:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:714:7
readURI/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/net/url.js:52:9
NetUtil_asyncFetch/<.onStopRequest@resource://gre/modules/NetUtil.jsm:128:17
"helpers.js:22
Aborted request for "b".recommendation-server.js:93
Aborted request for "bu".recommendation-server.js:93
Aborted request for "g".recommendation-server.js:93
Aborted request for "go".recommendation-server.js:93
Aborted request for "w".recommendation-server.js:93
Aborted request for "we".recommendation-server.js:93
Aborted request for "web".recommendation-server.js:93
Aborted request for "webr".recommendation-server.js:93
Aborted request for "webrt".recommendation-server.js:93
Aborted request for "webrtc".recommendation-server.js:93
Aborted request for "t".recommendation-server.js:93
Aborted request for "tr".recommendation-server.js:93
Aborted request for "tre".recommendation-server.js:93
Aborted request for "tree".recommendation-server.js:93
Aborted request for "trees".recommendation-server.js:93
Aborted request for "me".recommendation-server.js:93
Aborted request for "met".recommendation-server.js:93
Aborted request for "me".recommendation-server.js:93
Aborted request for "met".recommendation-server.js:93
Aborted request for "me".recommendation-server.js:93
Aborted request for "met".recommendation-server.js:93
"Handler function threw an exception: TypeError: this.transport is null
Stack: DSC_send@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1391:5
NEA_addSecurityInfo@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/webconsole.js:2136:5
NetworkResponseListener.prototype._getSecurityInfo<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:266:5
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
NetworkResponseListener.prototype.onStartRequest@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:215:5
Line: 1391, column: 5"ThreadSafeDevToolsUtils.js:80
Aborted request for "me".recommendation-server.js:93
Aborted request for "met".recommendation-server.js:93
unsafe CPOW usageverticaltabs.jsm:130
Content Security Policy: La directive « frame-src » est obsolète. Veuillez utiliser la directive « child-src » à la place.(source inconnue)
Une chaîne vide a été transmise à « getElementById() ».github-207236d9c34ff5ba0c5941f877df52c9b53c4ddad9a125c5d2094fed3300ea17.js:5:19672
Une chaîne vide a été transmise à « getElementById() ».frameworks-7fabbae774a2bd1d0d1b9416ee3e5e76d972482e598730893e49ef6024d87fa1.js:10:4099
unsafe CPOW usageRemoteAddonsParent.jsm:861:2
unsafe CPOW usageverticaltabs.jsm:130
unsafe CPOW usageRemoteAddonsParent.jsm:861:2
unsafe CPOW usageverticaltabs.jsm:130
TypeError: NetworkError when attempting to fetch resource.(source inconnue)
Missing onHighlightFinished callback on RemoteFinderListener
RemoteFinder.jsm:94
l[callback] is undefined
RemoteFinder.jsm:91
Une chaîne vide a été transmise à « getElementById() ».frameworks-7fabbae774a2bd1d0d1b9416ee3e5e76d972482e598730893e49ef6024d87fa1.js:10:4099
TypeError: NetworkError when attempting to fetch resource.(source inconnue)
Une chaîne vide a été transmise à « getElementById() ».github-207236d9c34ff5ba0c5941f877df52c9b53c4ddad9a125c5d2094fed3300ea17.js:5:19672
Une chaîne vide a été transmise à « getElementById() ».frameworks-7fabbae774a2bd1d0d1b9416ee3e5e76d972482e598730893e49ef6024d87fa1.js:10:4099
unsafe CPOW usageRemoteAddonsParent.jsm:861:2
unsafe CPOW usageverticaltabs.jsm:130
TypeError: NetworkError when attempting to fetch resource.(source inconnue)
unsafe CPOW usageRemoteAddonsParent.jsm:861:2
unsafe CPOW usageverticaltabs.jsm:130
Aborted request for "me".recommendation-server.js:93
Aborted request for "meo".recommendation-server.js:93
Aborted request for "meot".recommendation-server.js:93
Aborted request for "meote".recommendation-server.js:93
Aborted request for "meot".recommendation-server.js:93
Aborted request for "meo".recommendation-server.js:93
Aborted request for "me".recommendation-server.js:93
Aborted request for "mee".recommendation-server.js:93
Aborted request for "meet".recommendation-server.js:93
Aborted request for "meete".recommendation-server.js:93
Aborted request for "meeteo".recommendation-server.js:93
Aborted request for "meete".recommendation-server.js:93
Aborted request for "meet".recommendation-server.js:93
Aborted request for "mee".recommendation-server.js:93
Aborted request for "me".recommendation-server.js:93
TypeError: resultRows[newIndex] is undefined
highlight-manager.js:286:7
No recommendation available for "meteofrance.com".recommendation-server.js:93
No recommendation available for "meteofrance.com/".recommendation-server.js:93
Aborted request for "meteofrance.com".recommendation-server.js:93
Aborted request for "meteofrance.co".recommendation-server.js:93
Aborted request for "meteofrance.c".recommendation-server.js:93
Aborted request for "meteofrance.".recommendation-server.js:93
Aborted request for "meteofrance.c".recommendation-server.js:93
Aborted request for "meteofrance.co".recommendation-server.js:93
No recommendation available for "meteofrance.com".recommendation-server.js:93
Aborted request for "me".recommendation-server.js:93
Aborted request for "a".recommendation-server.js:93
Aborted request for "ab".recommendation-server.js:93
Aborted request for "abo".recommendation-server.js:93
unsafe CPOW usageRemoteAddonsParent.jsm:861:2
unsafe CPOW usageverticaltabs.jsm:130
Aborted request for "abou".recommendation-server.js:93
Aborted request for "about".recommendation-server.js:93
Aborted request for "about:".recommendation-server.js:93
Aborted request for "about:b".recommendation-server.js:93
Aborted request for "about:bu".recommendation-server.js:93
Aborted request for "about:bui".recommendation-server.js:93
Aborted request for "about:buil".recommendation-server.js:93
Aborted request for "about:build".recommendation-server.js:93
Aborted request for "about:buildc".recommendation-server.js:93
Aborted request for "about:buildco".recommendation-server.js:93
Aborted request for "about:buildcon".recommendation-server.js:93
Aborted request for "about:buildconf".recommendation-server.js:93
Aborted request for "about:buildconfi".recommendation-server.js:93
No recommendation available for "about:buildconfig".recommendation-server.js:93
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri May 20 2016 10:56:57 GMT+0200 (CEST)
Full Message: TypeError: ContentSearch._currentStateObj is not a function
Full Stack: get state/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/SearchProvider.js:55:25
TaskImpl_run@resource://gre/modules/Task.jsm:319:40
TaskImpl@resource://gre/modules/Task.jsm:280:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:254:14
Task_spawn@resource://gre/modules/Task.jsm:168:12
get state@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/SearchProvider.js:54:12
_respondToSearchRequests@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:161:9
EventEmitter_emit@resource://devtools/shared/event-emitter.js:163:11
_setupPageMod/this._pagemod<.onAttach/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:400:11
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker.js:74:26
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:96:37
SearchProvider.js:55
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri May 20 2016 10:57:33 GMT+0200 (CEST)
Full Message: TypeError: ContentSearch._currentStateObj is not a function
Full Stack: get state/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/SearchProvider.js:55:25
TaskImpl_run@resource://gre/modules/Task.jsm:319:40
TaskImpl@resource://gre/modules/Task.jsm:280:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:254:14
Task_spawn@resource://gre/modules/Task.jsm:168:12
get state@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/SearchProvider.js:54:12
_respondToSearchRequests@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:161:9
EventEmitter_emit@resource://devtools/shared/event-emitter.js:163:11
_setupPageMod/this._pagemod<.onAttach/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:400:11
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker.js:74:26
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:96:37
SearchProvider.js:55
Ce site utilise un certificat SHA-1 ; il est recommandé d’utiliser des certificats possédant des algorithmes de signature ayant recours à des fonctions de hachage plus robustes que SHA-1.[En savoir plus]/
L’API de la console de journalisation (console.log, console.info, console.warn, console.error) a été désactivée par un script sur cette page.

**Comment by jaredhirsch** [comment]
Thanks for filing this bug! It sounds like you were seeing no results in the awesomebar popup. That's a known issue (#164) and a fix has just landed (#230).

This should be fixed with the next update to the add-on early next week. Closing.
