### ISSUE TITLE
When mutliple browser windows are opened , and user selects alt +f and exit all the windows are closed

### ISSUE THREAD

**Issue by chandrasb1** [mozilla/universal-search#237]
When multiple browser windows are opened , and user selects alt +f and exit on the second browser all the windows are closed

**Comment by chuckharmston** [comment]
Thanks for the report, @chandrasb1!

I'm not able to reproduce this; would you mind giving more information about your operating system, Firefox version, and Firefox channel?

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
