### ISSUE TITLE
Disabling Universal Search should restore the "search" box to the toolbar

### ISSUE THREAD

**Issue by rfk** [mozilla/universal-search#242]
I disabled Universal Search through the TestPilot UI, but it didn't give me back the sepearate "search" box next to the URL bar.  I was very confused for about five minutes until I realized I had to go into the hamburger menu, click "customize", and drag it back out somewhere visible.  It would be nice if the addon remembered that I had this box visible originally and restored it when disabled.

**Comment by chuckharmston** [comment]
Hmmm...it [should be doing that already](https://github.com/mozilla/universal-search/blob/master/lib/universal-search.js#L99-L105). Definitely a bug, thanks for filing.

**Comment by kumar303** [comment]
This happened to me as well. Thanks for the workaround :)

**Comment by dveditz** [comment]
Thanks for the workaround

**Comment by davidhedlund** [comment]
https://github.com/mozilla/universal-search/issues/202

**Comment by davidhedlund** [comment]
This issue first appeared in [#202](https://github.com/mozilla/universal-search/issues/202) so you can close this issue @chuckharmston.

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
