### ISSUE TITLE
Universal Search sends "lots" of telemetry pings

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#246]
This is a pretty subjective and rubbish bug, but in testing some Telemetry ping stuff, I noticed that during regular usage of Universal Search, it would often send pings every 10 seconds if I was searching for stuff, or in some cases sending a 3 pings within a 6 second timespan.

Not sure if there is a way to reduce or combine the ping data to avoid potentially flooding the telemetry server.

![telemetry_data_and_search_results_and_firefox_test_pilot_-_universal_search](https://cloud.githubusercontent.com/assets/557895/15761287/3a9075ba-28cc-11e6-8040-8e52550d7cc5.png)

**Comment by chuckharmston** [comment]
The plan, as I understand it, is to actually rework this on the Test Pilot/telemetry side to be more accommodating for the event-driven pings that we have here, e.g. https://github.com/clouserw/testpilot/compare/master...metricsv2

Closing in favor of that. Thanks for the report!
