### ISSUE TITLE
No chrome package registered for chrome://myaddon/locale/mydialog.dtd

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#247]
### Steps to reproduce:
1. Open Browser Console
2. Install Test Pilot and Universal Search add-on.
3. Go to about:addons
4. Click the [Preferences] button for Universal Search
5. 👀 at the Browser Console output.
### Actual results:

The following is displayed in the Browser Console:

> _No chrome package registered for chrome://myaddon/locale/mydialog.dtd_

My best guess (which usually aren't very good), is that this is coming from [/chrome/content/preferences.xul:3](https://github.com/mozilla/universal-search/blob/af3fe337dde04bb2520406e0449c06e8c116cefc/chrome/content/preferences.xul#L3).
### Expected results:

I literally have no idea. Not sure if it even matters, but I'm a firm believer of "see something, say something" so thought I'd throw a flag.

**Comment by jaredhirsch** [comment]
@pdehaan Good guess! I'd say you are right. Any chrome URLs defined by this add-on should be mapped back to filesystem paths [inside chrome.manifest](https://github.com/mozilla/universal-search/blob/master/chrome.manifest).
