### ISSUE TITLE
Awesomebar suggestions, apart from universal result, disappear when US is enabled

### ISSUE THREAD

**Issue by mcomella** [mozilla/universal-search#253]
Unfortunately, a consistent STR is unknown. Generally it happens within 30 minutes or so of using Firefox.

I'm currently running Developer Edition 49.0a2 on OS X 10.10.5.

<img width="957" alt="screen shot 2016-06-16 at 22 11 10" src="https://cloud.githubusercontent.com/assets/759372/16133557/6bf87590-3410-11e6-82c4-65ee0ac1f4bc.png">

US = universal search

**Comment by chuckharmston** [comment]
Thanks for the report! Closing in favor of the original report of this: #164
