### ISSUE TITLE
Address bar results window has only one or two entries: TypeError: rows[(numRows - 1)] is undefined

### ISSUE THREAD

**Issue by cpeterso** [mozilla/universal-search#254]
I still see something like issue #164 with Universal Search version 1.0.6: the address bar results window has only one or two entries. When typing in the address bar, I see tons of JavaScript TypeErrors in the Firefox browser console from autocomplete code:

```
TypeError: rows[(numRows - 1)] is undefined. autocomplete.xml:1187:17
adjustHeight() autocomplete.xml:1187
_invalidate/this._adjustHeightTimeout<() autocomplete.xml:1115
```

**Comment by chuckharmston** [comment]
Thanks for the report!

Closing in favor of the original bug you cited for this: #164
