### ISSUE TITLE
tab mix plus + universalsearch = two tabs

### ISSUE THREAD

**Issue by pvinis** [mozilla/universal-search#255]
When I have the option for tab opening event for open tab from address bar, it works but it opens two new tabs. It should only have one new tab as before.

Steps to reproduce:
- have latest firefox beta
- have latest tmp dev build
- go to http://testpilot.firefox.com/ and install the test pilot addon
- go to https://testpilot.firefox.com/experiments/universal-search and install the universal search addon

Now, here are two configs for TMP:
First one is the buggy one, where two tabs open. thats the pvinis-two-tabs.txt
[pvinis-two-tabs.txt](https://github.com/mozilla/universal-search/files/334311/pvinis-two-tabs.txt)
Second one is with the i-guess-buggy part disable. (diff them if you want. the only difference is the tab opening event for new tab from address bar disabled option). thats the pvinis-no-tabs.txt
[pvinis-no-tabs.txt](https://github.com/mozilla/universal-search/files/334310/pvinis-no-tabs.txt)

So using the first config, i do cmd-l to go to focus on address bar. then i type "test". then hit enter.
i then get two new tabs instead of one.

i noticed that if i type something in the address bar, say "google" and then go down and select a site from the history, it correctly opens one tab. but if i type something and immediately hit enter, it opens two tabs going a google search of whatever i typed.

Since the address bar and search bar are one with the universal search, something there is confusing tmp tab opening? i dont know.

is that helpful? if you need more info, tell me. i can also make a video of it happening if thats helpful.

according to the dev, "for some reason the function `gURLBar.handleCommand` is triggered twice".

more info here:
http://tabmixplus.org/forum/viewtopic.php?f=2&t=19616

**Comment by chuckharmston** [comment]
Thanks for the report!

Unfortunately, I don't think it's likely that we'll have time to invest into compatibility with other add-ons while this remains an experiment. If this does matriculate into Firefox, we'll make sure to take a look.
