### ISSUE TITLE
Often blank autocomplete

### ISSUE THREAD

**Issue by peterbe** [mozilla/universal-search#256]
First of all, not sure if this belongs in "Cloud Services". 
Second of all, this problem only started appearing after enabling Universal Search in Test pilot. 

Here I'm typing the start of a URL I've typed many times before in recent days. It doesn't succeed in offering anything sometimes. 

The occurance is sporadic and feels like it's related to something sometimes getting unluckily stuck on network I/O.
<img width="1791" alt="screen shot 2016-06-27 at 2 17 40 pm" src="https://cloud.githubusercontent.com/assets/26739/16391148/d77f6b6e-3c73-11e6-8975-1679ae4b9095.png">

**Comment by chuckharmston** [comment]
Thanks for the report!

Closing in favor of the original bug: #164
