### ISSUE TITLE
Allow users to search secondary engines

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#259]
By removing the separate search box, we regress one piece of functionality: the ability to use multiple search engines.

<img width="243" alt="screen shot 2016-07-06 at 9 49 09 am" src="https://cloud.githubusercontent.com/assets/23885/16624694/f3891ad4-435e-11e6-9c6a-657ef04538a2.png">

This is something we should include in Universal Search. A similar interface that @shorlander has previously considered:

<img width="992" alt="screen shot 2016-07-06 at 9 46 14 am" src="https://cloud.githubusercontent.com/assets/23885/16624412/bc99044e-435e-11e6-850c-3fa5c2b80a28.png">

**Comment by shorlander** [comment]
We should have this functionality in Nightly soon. See https://bugzilla.mozilla.org/show_bug.cgi?id=1180944
