### ISSUE TITLE
Weird Telemetry Edge Cases

### ISSUE THREAD

**Issue by ghost** [mozilla/universal-search#262]
[RE:email with Chuck/Wil]

We have some data that seems to be invalid in Re:dash from Telemetry:
- Null values in any of the following: Didnavigate, Recommendationshown, Recommendationselected [0.03% of all packets]
- Recommendationshown != True AND Recommendationselected == True [0.01% of all packets]
- Recommendationselected == True AND Selectedindex != -1 [0.22% of all packets]
- Clock skewed/out of timeframe packets

For the time being Ilana is filtering her Telemetry job to get these out of Re:dash, but there may be upstream mitigations that are wanted.

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
