### ISSUE TITLE
You're breaking Firefox by unloading Console.jsm

### ISSUE THREAD

**Issue by gijsk** [mozilla/universal-search#267]
Please please please don't ever call `Cu.unload`. It's a bad idea, and it's led to multiple reports of brokenness (e.g. form submission inside Firefox breaks). You're calling it with a scope object - that's not how unload works: it just unloads all instances of the module everywhere (the instances are shared anyway). So the world breaks.

**Comment by gijsk** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1287824 for reference.

**Comment by jaredhirsch** [comment]
@gijsk Wow, this is really, really, really bad. Thank you so much for catching it. Do you think it'd be good to add some kind of comments to the `Cu.unload` docs on MDN?

**Comment by gijsk** [comment]
There is already a comment:

> You should not unload modules that are part of the application (anything under resource://gre/ or resource:/// or resource://app/) as these may be in use by other extensions and the application. Only unload modules you include as part of your extension.

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.unload

**Comment by jaredhirsch** [comment]
@gijsk Ah. Really unfortunate mistake on my part. Thanks again.

**Comment by gijsk** [comment]
@6a68 it's OK. One thing that I'm wondering about is whether you want to unload the add-on's stuff somewhere else when disabling one version of it to update it with a newer version? It's not clear to me if you're already doing that somewhere else or not.
