### ISSUE TITLE
Design the inserted recommendation.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#27]
We need to figure out how the inserted recommendation will actually look.

Bryan was going to dig up some prior art by shorlander and adapt it, if necessary.

**Comment by nchapman** [comment]
Mockups from @bryanbell:

<img width="672" alt="image 2016-02-18 at 3 47 41 pm" src="https://cloud.githubusercontent.com/assets/3095/13157641/0aa8d724-d657-11e5-8895-d9b0fdad501c.png">

<img width="672" alt="image 2016-02-18 at 3 47 56 pm" src="https://cloud.githubusercontent.com/assets/3095/13157646/11ef356e-d657-11e5-9c9c-312cebc9721a.png">

Ideally this would work as follows:
1. Never highlight a row by default
2. Hide the first result row (says either "Visit {domain}" or "{input text} - Search with {engine}")
3. Make the popup taller by the same amount as the recommendation row. It can stay this height all the time.

Those are in order of importance. Let us know if any of those sound terrible to implement :grin:.

**Comment by chuckharmston** [comment]
A few questions:
- Should we highlight string matches like in below results?
- What if an image isn't available? (Happens quite frequently.)
- Do we clip the corners of the image to round it, or is that how the Mozilla icon was made?
- Are the type sizes the same as the rows before? They look a bit different in the image, but that's probably just a mockup artifact.

**Comment by bryanbell** [comment]
> Should we highlight string matches like in below results?

Pretty sure we don't need this. 

> What if an image isn't available? (Happens quite frequently.)

![image fallback](https://cloud.githubusercontent.com/assets/228979/13160265/593e0b36-d664-11e5-9646-ac5e2fb34639.png)

> Do we clip the corners of the image to round it, or is that how the Mozilla icon was made?

I was clipping the corners in the mockup... that would be preferred. Do what you can. 

> Are the type sizes the same as the rows before? They look a bit different in the image, but that's 

probably just a mockup artifact.
It's officially taller. It needed to be cause we have to show the bottom line. and we need room around the suggested item so it doesn't feel cramped.

**Comment by chuckharmston** [comment]
@bryanbell that should work great, thanks for the effort!

Proposal: when we use the dominant favicon color, we use black text if the brightness of that color is >= 75, and white otherwise. That's how this plays out:

![75](https://cloud.githubusercontent.com/assets/23885/13182141/8c472f24-d6ed-11e5-9b5d-6ff984fba305.png)

(Columns drop from 100 to 60 in steps of 10).

**Comment by chuckharmston** [comment]
We have what we need here. Thanks,  Bryan!
