### ISSUE TITLE
Metrics: ts and activity_date *may* have strange discrepancies

### ISSUE THREAD

**Issue by ghost** [mozilla/universal-search#277]
(@ilanasegall @rjweiss)
activity_date has quite a bit of ping volume on either side of ts.  Not sure if this is just packet delays + clock skew or an actual issue.  Below is a comparison of the string casted dates + ping count.  I've filtered on days with >=100 pings, but there are a _lot_ more lower volume entries.  

Look at 6/15 for a serious example:
activity    ts  cnt
20160615    20160613    166
20160615    20160614    577
20160615    20160615    132824
20160615    20160616    332

[activity_vs_ts.csv.zip](https://github.com/mozilla/universal-search/files/385018/activity_vs_ts.csv.zip)

**Comment by jaredhirsch** [comment]
@rayborn Hi! I don't have much context here, but looking at what you've attached, on 6/15 the date-shifted pings add up to around 1% of the same-day pings. That seems like quite precise data, assuming it comes from ~150,000 different PCs with user-controlled clock settings ^_^

**Comment by jaredhirsch** [comment]
@rayborn Whoops, hit Enter a bit too quickly. Seriously, though - I'm curious what the typical date precision is with other Firefox client pings. Are you worried that some pings are getting dropped, or that the date being off points to something deeper?

**Comment by ghost** [comment]
@6a68 - I have no past experience with skew here to have a base level comparison.  Just wanted to raise what I was seeing to make sure that this sounded reasonable to those with more knowledge.

**Comment by ghost** [comment]
Also, for reporting purposes, should I use TS since this is event based telemetry which would imply that it is less likely to be off by non-negligible margins?

**Comment by jaredhirsch** [comment]
> @6a68 - I have no past experience with skew here to have a base level comparison. Just wanted to raise what I was seeing to make sure that this sounded reasonable to those with more knowledge.

Ah yeah, that makes sense. Good to log the little things as you happen across them :+1:
