### ISSUE TITLE
Subsequent searches in a new window show the search suggestions for the first entered keyword

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#279]
[Affected versions]:
- Firefox 45 and up
- Universal Search 1.0.8

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Universal Search add-on (v1.0.8) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a new window and type a keyword in the Awesome Bar (e.g. wikipedia).
3. Press "Enter" key in order to perform a search.
4. Click on "+" to open a new tab.
5. Type a different keyword in the Awesome Bar.
6. Observe the suggestions from the dropdown list.

[Expected result]:
- The dropdown list displays suggestions for the current entered keyword.

[Actual result]:
- The dropdown list displays suggestions for the first entered keyword instead for the current one.

[Notes]:
- The issue is also reproducible in a new Private Window.
- [Link](https://drive.google.com/file/d/0B70KzYmGg491Q0Z4WTlocFczTTA/view?pref=2&pli=1) for the screen recording that describes the issue.

**Comment by jaredhirsch** [comment]
@SoftVision-CosminMuntean This should be fixed in 1.0.9 as well. Could you try to repro again?

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible using the latest version of Universal Search (1.0.9) . I have tested this on the latest Firefox (48.0.2) release and latest Nightly (51.0a1) build.
