### ISSUE TITLE
Universal Search functionality still available after Test Pilot uninstallation if Tab Center experiment is instaled before it

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/universal-search#281]
[Affected versions]:
- Nightly 50.0a1
- Test Pilot 0.8.3 -tag-2016-07-29

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net page.
2. Click on the big green "Install the Test Pilot Add-on" button.
3. After the installation chose the "Tab Center" experiment and "Enable" it.
4. Return to "Experiments" page and choose the "Universal Search" experiment.
5. Enable it and after click on "Settings" button from top part of the page.
6. Choose to "Uninstall Test Pilot" and confirm the choice from "Proceed" button.
7. Observe the browser address bar after uninstall is finalized.

[Expected result]:
The browser address bar is split again in two different bars as default.

[Actual result]:
The browser address bar remains unchanged as if "Universal Search" experiment is still installed.

[Notes]:
- This only reproduces when "Tab Center" experiment is installed before Universal Search one.
- The "about:addons" page no longer displays any of the experiments as installed.
- Reproducible 5/5 tries. 
- Added a screen recording with the issue https://goo.gl/6DDrTi.

**Comment by SoftVision-PaulOiegas** [comment]
Browser console output when following the above steps.
https://pastebin.mozilla.org/8888867
@chuckharmston

**Comment by jaredhirsch** [comment]
this seems like a tab center bug to me? since tab center is breaking the CustomizableUI?

**Comment by SoftVision-PaulOiegas** [comment]
Another scenario that seems to have the same root cause. But it seams that Tab Center could be the real problem here.

[Steps]:
1. Go to https://testpilot.firefox.com page.
2. Click on the big green "Install the Test Pilot Add-on" button.
3. After the installation chose the "Tab Center" experiment and "Enable" it.
4. Disable the Tab Center experiment and return to Homepage.
5. Choose the "Universal Search" experiment and "Enable" it.
6. Observe the browser address bar after experiment is enabled.

[Expected result]:
The browser address bar is unified with the search bar.

[Actual result]:
The browser address bar remains unchanged.

[Notes]:
- This issue also occurs if the Universal Search is already enabled when disabling Tab Center. But in this case the unified bar won't split after disabling Universal Search as in the original bug.

**Comment by SoftVision-PaulOiegas** [comment]
Moving this to Tab Center repo (https://github.com/bwinton/VerticalTabs/issues/479).
