### ISSUE TITLE
The suggestions dropdown list is not displayed if previously the "Show History" button from the Awesome Bar is clicked after the browser was opened

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#284]
[Affected versions]:
- Firefox 45 and up
- Universal Search 1.0.8

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Universal Search add-on (v1.0.8) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Hover the Awesome Bar and click the "Show History" button from the end of the bar.
3. Dismiss the dropdown list or open a new tab. 
4. Type a keyword in the Awesome Bar.
5. Observe the the dropdown list.

[Expected result]:
- The dropdown list is displayed and contains a recommended website and suggestions for the entered keyword.

[Actual result]:
- The dropdown list is no longer displayed.

[Notes]:
- A screen recording describing the issue was attached: https://goo.gl/CQlnBx
- Browser console:
  ![console errors](https://cloud.githubusercontent.com/assets/19226534/17402010/8f7debde-5a59-11e6-8f50-8f7dba010c18.png)

**Comment by jaredhirsch** [comment]
@SoftVision-CosminMuntean Hey, could you try to reproduce this bug on the latest version, 1.0.9?

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on the latest version of Universal Search (1.0.9) . I have tested this on the latest Firefox (48.0.2) release and latest Nightly (51.0a1) build.
