### ISSUE TITLE
History dropmarker doesn't work

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#285]
[Affected versions]:
- Firefox 45 and up
- Universal Search 1.0.8

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Universal Search add-on (v1.0.8) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Hover the Awesome Bar and click the "Show History" button from the end of the bar.
3. Observe the the dropdown list.

[Expected result]:
- The latest visited websites are displayed in the dropdown list.

[Actual result]:
- The latest visited website are not displayed in the dropdown list, only the "Change Search Settings" button.

[Notes]:
- A screen recording describing the issue was attached: https://goo.gl/w3dsSu

**Comment by jaredhirsch** [comment]
Yup, this has been an open bug from the beginning. Our goal is not to make 100% of the urlbar features work, it's to preserve the main interactions and add a recommendation to them. As another example, we don't support the urlbar keyword shortcuts either. Closing as a wontfix, but thanks for filing :beers:
