### ISSUE TITLE
Suggestions are no longer displayed for written keywords in Awesome Bar

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#288]
[Notes]:
- I have noticed that even the "Change Search Settings" button is not displayed.
- Under the recommended website is displayed only the default search engine icon.
- I think that maybe bug [1180944](https://bugzilla.mozilla.org/show_bug.cgi?id=1180944) affected this functionality.

[Affected versions]:
- Firefox 45 and up
- Universal Search 1.0.8

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Universal Search add-on (v1.0.8) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Type a keyword in the Awesome Bar.
3. Observe the the dropdown list.

[Expected result]:
- The dropdown list is displayed and contains a recommended website and suggestions for the written keyword.

[Actual result]:
- The dropdown list is displayed and contains a recommended website but there are no suggestions for the written keyword.
- Screenshot of the issue: 

![no sugestions](https://cloud.githubusercontent.com/assets/19226534/17437437/5b3d5d64-5b26-11e6-88f2-103295f2dad6.png)

**Comment by SoftVision-EmilPasca** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1291999

**Comment by jaredhirsch** [comment]
same cause as #286, I think. closing--reopen if I'm wrong
