### ISSUE TITLE
Enter key stopped working in awesomebar with universal search installed

### ISSUE THREAD

**Issue by indygreg** [mozilla/universal-search#289]
Running Nightly 2016-08-04 and 2016-08-05 on Windows 10. The enter key no longer works in the awesomebar. So I can't navigate to sites by pressing enter.

The enter key still works in content.

The error reported in the browser console on press of the enter key is:

TypeError: this.popup.oneOffSearchButtons is null[Learn More]urlbarBindings.xml:370:1handleCommandchrome://browser/content/urlbarBindings.xml:370:1anonymouschrome://global/content/bindings/autocomplete.xml%20line%20421%20%3E%20Function:1:1bound anonymousself-hostedonTextEnteredchrome://global/content/bindings/autocomplete.xml:238:18handleEnterchrome://browser/content/urlbarBindings.xml:1032:22handleKeyPresschrome://global/content/bindings/autocomplete.xml:503:24onxblkeypresschrome://universalsearch/content/binding.xml:36:67

**Comment by lissyx** [comment]
dupe of #286
