### ISSUE TITLE
Universal Search should be marked as multiprocess compatible

### ISSUE THREAD

**Issue by Standard8** [mozilla/universal-search#291]
Currently Universal Search isn't marked as multiprocess compatible. Although it seems to work, there may still be some incompatibilities that are masked by Firefox's shims.

The shims may also lead to performance issues, although I doubt Universal Search would really be hitting those that hard: https://developer.mozilla.org/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK#Testing_with_shims_enabled

Setting the flag for Universal Search should be as simple as adding the following to `install.rdf`:

```
<em:multiprocessCompatible>true</em:multiprocessCompatible>
```

Obviously, it should be tested to make sure it does work.

**Comment by jaredhirsch** [comment]
@Standard8 Thanks for the suggestion! Pull requests welcome :-)

**Comment by Standard8** [comment]
@6a68 Although the "patch" is simple, I've found it really helps if someone who is familiar with the code does a short review against https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_chrome_scripts and also exercising the extension with the pref "dom.ipc.shims.enabledWarnings" set to true (and watching the browser console!) before the change.
