### ISSUE TITLE
No results appear in awesome bar

### ISSUE THREAD

**Issue by gaby2300** [mozilla/universal-search#303]
Windows 7, today's Nightly. 

I installed Universal Search form the Test Pilot icon, I opened a new tab and typed "radio" in the awesome bar. No results appeared.

**Comment by gaby2300** [comment]
Besides no results appearing, the URL bar didn't work at all: copying this issue's URL to have it in a new tab and pressing enter or clicking the bar's arrow  produced no results at all.

**Comment by chuckharmston** [comment]
Thanks for the report, @gaby2300! Nightly currently has some changes to the Awesome Bar that we haven't yet been able to accommodate. We're tracking this work in #286.

**Comment by gaby2300** [comment]
On 24 August 2016 at 16:47, Chuck Harmston notifications@github.com wrote:

​Thanks for letting me know! I'll be following ​#286
https://github.com/mozilla/universal-search/issues/286 then to know
whenever it's fixed.
