### ISSUE TITLE
Problems installing from link in changelog

### ISSUE THREAD

**Issue by bull500** [mozilla/universal-search#308]
Tried installing from  https://github.com/mozilla/universal-search/blob/master/docs/changelog.md

This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>0923BCD9F66A3152</RequestId><HostId>RYP8g9MSBIAZqBNuKUwtf88qr18Muvx9PZrHPnVp9rbdXmXTxVTDLYdR4eSYNgXcNW3N4DyC5Y4=</HostId></Error>

**Comment by bull500** [comment]
also the official page lists a very old version - https://testpilot.firefox.com/experiments/universal-search

**Comment by jaredhirsch** [comment]
@bull500 Thanks for the bug report. How exactly did you attempt to install the addon? Try to download it, then from about:addons, click the 'gear' menu, and choose 'install from file'. This works fine for me on Nightly / Mac. _Edit: or you could just install the addon from https://testpilot.firefox.com_

> also the official page lists a very old version - https://testpilot.firefox.com/experiments/universal-search

Yup, 1.0.9 is available if you we still need to update the main site. Thanks for the reminder.

_Edit: the test pilot site says the current version is 1.0.6, but if you install the search addon, you'll see that you actually download 1.0.9._

**Comment by bull500** [comment]
i tried to download/install from the link in the first post.  

yup its fixed now! Updated via the about:addons place.  
Before it was stuck on 1.0.8 and the 1.0.9 version was on the link so i tried that route .

**Comment by jaredhirsch** [comment]
@bull500 :tada: Great! closing
