### ISSUE TITLE
The Universal Search UI changes are not reverted if the add-on is removed after a restart

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/universal-search#311]
[Affected versions]:
- Firefox 48 and up
- Universal Search 1.0.9

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Steps to reproduce]:
1. Open Firefox with a new created profile. 
2. Install latest Universal Search add-on (v1.0.9) and after, restart the browser.
3. Go to "about:addons" at "Extensions" tab and choose to remove the Universal Search add-on.
4. Observe the address bar behavior.

[Expected result]:
- The add-on is removed and the browser address bar returns to default functionality (address bar + search bar).

[Actual result]:
- The add-on is removed but the browser address bar does not returns to default UI (address + search bar remain unified).

[Notes]
- This issue is also reproducible if the add-on is enabled from Test Pilot.
- Screenshot of the issue: https://goo.gl/xqLJQW.

**Comment by dveditz** [comment]
Is there any fix/workaround/recovery for this? This is not only bad for Universal Search it will make people--or at least me!--shy away from trying other Test Pilot experiments if they can't be tried without risk.

**Comment by jaredhirsch** [comment]
To get the search bar back, open up the Customize menu and drag the search bar back into the toolbar.

This SUMO page has more details and screenshots: https://support.mozilla.org/kb/customize-firefox-controls-buttons-and-toolbars
