### ISSUE TITLE
Dot bump for e10s flag

### ISSUE THREAD

**Issue by johngruen** [mozilla/universal-search#312]
@chuckharmston hey Chuck, can you add a dot bump for that e10s compat flag? We need a minimum version for the whitelist, and i'd like to keep it separate.

@clouserw once we get this can we package the XPI and update prod?

**Comment by chuckharmston** [comment]
@johngruen It will/would be `1.0.10`. I was waiting to get the okay to move forward with the e10s flag (which I think is still pending?), since we wouldn't want a release if we have to back it out.

**Comment by ghost** [comment]
Sounds like it works, so yes, let's ship this.  Is there any other code to go out at the same time?
