### ISSUE TITLE
Alt-enter opens two tabs instead of just one

### ISSUE THREAD

**Issue by orens** [mozilla/universal-search#314]
When activating universal-search, pressing Alt-Enter opens two identical tabs instead of just one.
I verified it by disabling-checking-re-enabling-checking, several times. When universal-search is disabled, it doesn't happen. However, when enabled, it happens **_almost**_ every time I press Alt-Enter in the address bar.

System details below. Please let me know if there is any additional info I should add.
## Application Basics

Name: Firefox
Version: 48.0.1
Build ID: 20160817112116
Update Channel: release
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0
OS: Darwin 15.6.0 x86-64
Multiprocess Windows: 0/17 (Disabled by add-ons)
Safe Mode: false
## Crash Reports for the Last 3 Days

All Crash Reports
## Extensions

Name: about:addons-memory
Version: 12
Enabled: true
ID: about-addons-memory@tn123.org

Name: Activity Stream
Version: 1.1.3
Enabled: true
ID: @activity-streams

Name: Adblock Plus
Version: 2.7.3
Enabled: true
ID: {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}

Name: AngScope - Simple AngularJS Scope Inspector for Firebug
Version: 0.1.2.1-signed.1-signed
Enabled: true
ID: angscopefb@gmail.com

Name: Awesome Screenshot - Capture, Annotate & More
Version: 3.0.11
Enabled: true
ID: jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack

Name: CodeBurner for Firebug
Version: 1.6.1-signed.1-signed
Enabled: true
ID: firebug@tools.sitepoint.com

Name: Customizable Shortcuts
Version: 0.9.8
Enabled: true
ID: customizable-shortcuts@timtaubert.de

Name: DownThemAll!
Version: 3.0.6
Enabled: true
ID: {DDC359D1-844A-42a7-9AA1-88A850A938A8}

Name: Firebug
Version: 2.0.17
Enabled: true
ID: firebug@software.joehewitt.com

Name: Firefox Hello Beta
Version: 1.4.4
Enabled: true
ID: loop@mozilla.org

Name: Greasemonkey
Version: 3.9
Enabled: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: Less Spam, please
Version: 0.8.0.1-signed.1-signed
Enabled: true
ID: lessspamplease@developer.org

Name: Lightbeam
Version: 1.3.1
Enabled: true
ID: jid1-F9UJ2thwoAm5gQ@jetpack

Name: Master Password+
Version: 1.22
Enabled: true
ID: masterpasswordtimeoutplus@vano

Name: Multi-process staged rollout
Version: 1.2
Enabled: true
ID: e10srollout@mozilla.org

Name: Nightly Tester Tools
Version: 3.8
Enabled: true
ID: {8620c15f-30dc-4dba-a131-7c5d20cf4a29}

Name: No More 404s
Version: 1.5.6
Enabled: true
ID: wayback_machine@mozilla.org

Name: OneTab
Version: 1.17.0
Enabled: true
ID: extension@one-tab.com

Name: Pixel Perfect
Version: 2.0.14
Enabled: true
ID: pixelperfectplugin@openhouseconcepts.com

Name: Pocket
Version: 1.0.4
Enabled: true
ID: firefox@getpocket.com

Name: ProfileSwitcher
Version: 1.7.6.1
Enabled: true
ID: {fa8476cf-a98c-4e08-99b4-65a69cb4b7d4}

Name: Pushbullet
Version: 316
Enabled: true
ID: jid1-BYcQOfYfmBMd9A@jetpack

Name: QuickMark
Version: 1.2.10
Enabled: true
ID: jid0-QT2VXewB9xzbRlyapSJjA4ebwoU@jetpack

Name: RightToClick
Version: 2.9.6
Enabled: true
ID: {cd617375-6743-4ee8-bac4-fbf10f35729e}

Name: Roomy Bookmarks Toolbar
Version: 1.4.11
Enabled: true
ID: ALone-live@ya.ru

Name: Save File to
Version: 2.5.5
Enabled: true
ID: savefileto@mozdev.org

Name: SSL Version Control
Version: 0.4.1-signed
Enabled: true
ID: jid1-ZM3BerwS6FsQAg@jetpack

Name: Test Pilot
Version: 0.8.5-tag-2016-09-12
Enabled: true
ID: @testpilot-addon

Name: Tile Tabs
Version: 14.3
Enabled: true
ID: tiletabs@DW-dev

Name: Todoist: To-Do list and Task Manager
Version: 4.0.5
Enabled: true
ID: support@todoist.com

Name: Universal Search
Version: 1.0.10
Enabled: true
ID: universal-search@mozilla.com

Name: Flashblock
Version: 1.5.20
Enabled: false
ID: {3d7eb24f-2740-49df-8937-200b1cc08f8a}

Name: Google™ Hangouts
Version: 0.1.6
Enabled: false
ID: jid1-uqbSKwXpf2K6yl@jetpack

Name: Reload Plus
Version: 5.1.0
Enabled: false
ID: reloadplus@blackwind
## Graphics

Features
Compositing: OpenGL
Asynchronous Pan/Zoom: none
WebGL Renderer: NVIDIA Corporation -- NVIDIA GeForce GT 750M OpenGL Engine
Hardware H264 Decoding: Yes
GPU #1
Active: Yes
Vendor ID: 0x10de
Device ID: 0x0fe9

Diagnostics
AzureCanvasAccelerated: 1
AzureCanvasBackend: skia
AzureContentBackend: skia
AzureFallbackCanvasBackend: none
## Important Modified Preferences

accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.hashstats_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 2
browser.download.folderList: 2
browser.download.importedFromSqlite: true
browser.fixup.domainwhitelist.box: true
browser.fixup.domainwhitelist.southpark: true
browser.fixup.domainwhitelist.ubuntu: true
browser.places.smartBookmarksVersion: 8
browser.sessionstore.upgradeBackup.latestBuildID: 20160817112116
browser.startup.homepage: resource://activity-streams/data/content/activity-streams.html#/
browser.startup.homepage_override.buildID: 20160817112116
browser.startup.homepage_override.mstone: 48.0.1
browser.tabs.remote.autostart.2: true
browser.tabs.warnOnClose: false
browser.urlbar.suggest.bookmark: false
browser.urlbar.suggest.searches: true
browser.urlbar.userMadeSearchSuggestionsChoice: true
dom.apps.reset-permissions: true
dom.mozApps.used: true
dom.push.userAgentID: 1178e82fbd1849c3b838a162b791a0be
extensions.lastAppVersion: 48.0.1
font.internaluseonly.changed: false
gfx.blacklist.direct2d.failureid: FEATURE_FAILURE_DL_BLACKLIST_g984
gfx.crash-guard.glcontext.appVersion: 45.0.2
gfx.crash-guard.glcontext.deviceID: 0x0d26
gfx.crash-guard.status.glcontext: 2
media.benchmark.vp9.fps: 215
media.benchmark.vp9.versioncheck: 1
media.gmp-gmpopenh264.abi: x86_64-gcc3-u-i386-x86_64
media.gmp-gmpopenh264.lastUpdate: 1471464804
media.gmp-gmpopenh264.version: 1.6
media.gmp-manager.buildID: 20160817112116
media.gmp-manager.lastCheck: 1474190342
media.gmp-widevinecdm.abi: x86_64-gcc3-u-i386-x86_64
media.gmp-widevinecdm.lastUpdate: 1465741569
media.gmp-widevinecdm.version: 1.4.8.866
media.gmp.storage.version.observed: 1
media.webrtc.debug.aec_log_dir: /Users/orens/Library/Caches/TemporaryItems
media.webrtc.debug.log_file: /Users/orens/Library/Caches/TemporaryItems/WebRTC.log
media.youtube-ua.override.to: 43
network.auth.allow-subresource-auth: 2
network.cookie.prefsMigrated: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1473351597
places.favicons.optimizeToDimension: 64
places.history.expiration.transient_current_max_pages: 104858
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
print.print_bgcolor: false
print.print_bgimages: false
print.print_colorspace:
print.print_command:
print.print_downloadfonts: false
print.print_duplex: 1515870810
print.print_evenpages: true
print.print_in_color: true
print.print_margin_bottom: 0.5
print.print_margin_left: 0.5
print.print_margin_right: 0.5
print.print_margin_top: 0.5
print.print_oddpages: true
print.print_orientation: 0
print.print_page_delay: 50
print.print_paper_data: 0
print.print_paper_height: 11.00
print.print_paper_name:
print.print_paper_size_type: 1
print.print_paper_size_unit: 0
print.print_paper_width: 8.50
print.print_plex_name:
print.print_resolution: 1515870810
print.print_resolution_name:
print.print_reversed: false
print.print_scaling: 1.00
print.print_shrink_to_fit: false
print.print_to_file: false
print.print_unwriteable_margin_bottom: 17
print.print_unwriteable_margin_left: 25
print.print_unwriteable_margin_right: 25
print.print_unwriteable_margin_top: 17
privacy.sanitize.migrateClearSavedPwdsOnExit: true
privacy.sanitize.migrateFx3Prefs: true
services.sync.declinedEngines: prefs,addons
services.sync.engine.adblockplus: true
services.sync.engine.addons: false
services.sync.engine.greasemonkey: true
services.sync.engine.prefs: false
services.sync.engine.prefs.modified: false
services.sync.lastPing: 1474189482
services.sync.lastSync: Sun Sep 18 2016 12:20:02 GMT+0300 (IDT)
services.sync.numClients: 2
social.enabledByActivityStream: true
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1472653861
storage.vacuum.last.queue.sqlite: 1473858213
## JavaScript

Incremental GC: true
## Accessibility

Activated: false
Prevent Accessibility: 0
## Library Versions

NSPR
Expected minimum version: 4.12
Version in use: 4.12

NSS
Expected minimum version: 3.24 Basic ECC
Version in use: 3.24 Basic ECC

NSSSMIME
Expected minimum version: 3.24 Basic ECC
Version in use: 3.24 Basic ECC

NSSSSL
Expected minimum version: 3.24 Basic ECC
Version in use: 3.24 Basic ECC

NSSUTIL
Expected minimum version: 3.24
Version in use: 3.24

**Comment by SoftVision-PaulOiegas** [comment]
Thanks for the report! I can confirm that this is reproducible also on my end. I have just tested it with a custom build made from the repo today.
All you need to do is to install Universal Search, and press Alt+ Enter key combination after clicking the website URL in the address bar.

**Comment by orens** [comment]
Any news?

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
