### ISSUE TITLE
Wikipedia and imdb fight to display the movie recommendation

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/universal-search#317]
[Affected versions]:
- Nightly  52.0a1
- Universal Search v1.0.10 (build date 10.03.2016)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "xpinstall.signatures.required" pref was set to false on a new clean profile
- Universal Search build with movie cards was installed on the profile.
- Added boolean "window.universalSearch.variants.movieCard" pref with "true" value.
- Universal Search add-on was set to point on"Staging" server from "abbout:addons" details page.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and click the unified address bar.
2. Enter "incep" string and observe the results.
3. Continue the string and enter "t" letter while observing the results.
4. Continue the string and enter "i" and "o" letters while observing the results.
5. Complete the movie name and enter "n" character while observing the results.

[Expected result]:
- Step 2: Inception movie is displayed as a Wikipedia result.
- Step 3: For the next letter, Inception movie is displayed as an Imdb result.
- Step 4: For both letters, Inception movie is again displayed as Wikipedia result.
- Step 5: For the last letter, Inception movie is again displayed as an Imdb result.

[Actual result]:
- After a partial string is recognized as an Imdb movie result, it should always be displayed as one if the right characters are entered.

[Notes]:
- Added a screen recording with the issue https://goo.gl/NyquQY.

**Comment by chuckharmston** [comment]
https://universalsearch.stage.mozaws.net/?q=incep
https://universalsearch.stage.mozaws.net/debug?q=incep

Because the `Response` section in the former is different than the content of the latter, it seems likely that memcached was not flushed on the deploy. The alternation you see is switching back and forth between wikipedia and movie entries is actually probably alternation between entries that were in the cache with old data, and ones that weren't.

I'll get ops to flush memcached this morning and verify before closing.

**Comment by SoftVision-PaulOiegas** [comment]
We are seeing another two issues:
1. Websites favicons. You have a recommendation from Imdb (link displayed) but the favicon displayed is for CBS, History, etc. 
2. Entering a partial movie title displays the recommendation, but entering the full name (more than 1 word) removes the recommendation.

Do you think that these are also caused by the same root cause or should we log separate issues for both of them ?

**Comment by chuckharmston** [comment]
Both separate bugs, please log!

**Comment by chuckharmston** [comment]
This should be fixed now.
