### ISSUE TITLE
Can't select entries in the address bar's drop-down list in Nightly 52

### ISSUE THREAD

**Issue by cpeterso** [mozilla/universal-search#322]
STR:
1. Enable the Universal Search add-on version 1.0.11.
2. Enter some text in the address bar.
3. Use the arrow keys to select a page in address bar's drop-down list.

RESULT:
The selected page is not loaded. Instead, the entered text is passed to my default search provider. You _can_ select a page from the drop-down list using the mouse.

This is a regression from [Firefox bug 1306639](https://bugzilla.mozilla.org/show_bug.cgi?id=1306639) in Firefox Nightly 52. Disabling the Universal Search add-on fixes the problem.

**Comment by jaredhirsch** [comment]
@cpeterso Thanks for filing this bug! A fix is incoming.

**Comment by chuckharmston** [comment]
@cpeterso We just released 1.0.12, which should fix this. Mind verifying?

**Comment by cpeterso** [comment]
1.0.12 works for me! 👍
