### ISSUE TITLE
Stack title and url (again)

### ISSUE THREAD

**Issue by BigBlueHat** [mozilla/universal-search#324]
The screenshots for Universal Search had me hopeful that it would/could stack the title and URL the way the Awesome Bar did things pre-45:

![the really awesome bar](https://testpilot.firefox.com/static/images/experiments/universal-search/experiments_experimentdetail/6/d/6d0ff50eff9223f0d0cc58c5aa5d0c81_image_1462827811_0995.2389d5e5.jpg)

Sadly (for me at least) it seems it leaves things on the very-wide (when full screen) or terribly truncated (just title on narrow windows) location result format introduced in Firefox 45.

Are there plans to support the old style layout (can an extension fix that)? or are those screenshots just old...?

Thanks!
🎩

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
