### ISSUE TITLE
"No recommendation available" for everything?

### ISSUE THREAD

**Issue by NickMackz** [mozilla/universal-search#327]
Windows 10
Firefox 49.0.2

Add-ons:
- Lastpass
- Min Vid
- Reddit Enhancement Suite
- Strict Pop-up Blocker
- Tab Groups
- Test Pilot
- uBlock Origin
- WOT

Just installed this from Test Pilot and tried a few searches and no recommendations are showing up and the console reports 'No recommendation available' for anything I try.

**Comment by Smultie** [comment]
I have the same at the moment. 
Yesterday it worked

**Comment by chuckharmston** [comment]
We do avoid showing recommendations in a few cases:
- The connection to the server isn't fast enough that we can generate and show it without being disruptive.
- The recommendation already exists (i.e. as a bookmark or history item) in the Awesome Bar.
- We don't have a good recommendation for the search term.

Here, I think it's likely one of those things. The server [appears to be up and running](https://universalsearch.testpilot.firefox.com/?q=f) and providing recommendations as expected. I'm going to close this, but would be happy to reopen or file new issues it if we can come up with specific examples where it isn't behaving as you'd expect.

Thanks for the report, @NickMackz and @Smultie!
