### ISSUE TITLE
issue with search bar

### ISSUE THREAD

**Issue by localbroadcast** [mozilla/universal-search#329]
### On what OS did you encounter this issue?

windows 7 home premium
### What version of Firefox are you using?

uh.. 47.0.1 holy shit thats alota verszzzons
### Please list all add-ons you have installed in Firefox

uh... no.
### Are there any errors showing in the developer console?

uh... no idea.  just that I usually like to have a small search bar at the top of my browser beside the address bar, this way I can type stuff in there and then pull down the menu and select which site i want to search that keyword on.  useful for comparison searching amazon ebay etc. for pricing as well as other reasons.  for some reason, when I have the universal search thing enabled, even if I put this search bar where i usually keep it, when i restart firefox, it will remove this from where i put it!  i'll have to go back into customize and pull it out again.  took me a while to figure out that it was the universal search causing this issue.  annoying!!  anyways.. i dont really know if universal search ever did anything for me at all... never noticed anythign different when it was enabled except that my damn search bar kept dissapearing on me.  good luck!

**Comment by jaredhirsch** [comment]
Hi, the universal search addon indeed removes the separate search bar. You can restore it by removing universal search.
