### ISSUE TITLE
Unable to get it work

### ISSUE THREAD

**Issue by Ludomancer** [mozilla/universal-search#330]
Basically the url bar doesn't show anything new or suggest anything that Firefox didn't do before. I've tested a few queries with no results. See below, I would expect IMDB suggestion for "The Martian" and NetFlix suggestion for, "Net" query.

![issues_ _mozillauniversal-search_-_nightly 20161030 223017](https://cloud.githubusercontent.com/assets/6220948/19839340/f03ceee4-9ef0-11e6-8dab-b362268e2d0a.png)
![issues_ _mozillauniversal-search_-_nightly 20161030 222959](https://cloud.githubusercontent.com/assets/6220948/19839339/f03845b0-9ef0-11e6-94e2-2bd498e6f261.png)
### On what OS did you encounter this issue?

Windows 10 Anniversary Update 14393.351
### What version of Firefox are you using?

52.0a1 (2016-10-05) (64-bit)
### Please list all add-ons you have installed in Firefox

Activity Stream 1.1.5   true    @activity-streams
Add to Search Bar   2.9 true    add-to-searchbox@maltekraus.de
Add-on Compatibility Reporter   2.2.2   true    compatibility@addons.mozilla.org
checkCompatibility  1.3.1-signed.1-signed   true    check-compatibility@dactyl.googlecode.com
Decentraleyes   1.3.5   true    jid1-BoFifL9Vbdl2zQ@jetpack
FlyWeb  1.0.0   true    flyweb@mozilla.org
Form Autofill   1.0 true    formautofill@mozilla.org
HTTPS Everywhere    5.2.6   true    https-everywhere@eff.org
Imagus  0.9.8.46    true    {00000f2a-7cde-4f20-83ed-434fcb420d71}
LastPass    4.1.29a true    support@lastpass.com
Min Vid 0.3.3   true    @min-vid
Multi-process staged rollout    1.4 true    e10srollout@mozilla.org
No More 404s    1.5.6   true    wayback_machine@mozilla.org
Notifier for GitHub 1.4.1   true    jid1-DMjSwVBPnk7a1Q@jetpack
Page Shot   1.0.201610251521    true    jid1-NeEaf3sAHdKHPA@jetpack
Pin It button   1.37.9  true    jid1-YcMV6ngYmQRA2w@jetpack
Places Maintenance  2.0.2   true    places-maintenance@bonardo.net
Pocket  1.0.5   true    firefox@getpocket.com
Quick Context Search    1.5.4   true    quickcontextsearch@pf
Reddit Enhancement Suite    5.0.3   true    jid1-xUfzOsOFlzSOXg@jetpack
Restart 1.2.8   true    Restart@schuzak.jp
Save File to    2.5.5   true    savefileto@mozdev.org
Stylish 2.0.7b1 true    {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}
Test Pilot  0.8.9-dev-64c00d1   true    @testpilot-addon
Tracking Protection Experiment  1.0.1   true    blok@mozilla.org
trello-card-numbers 1.0.1-signed.1-signed   true    jid1-jvS1Yxjh3c6VUw@jetpack
uBlock Origin   1.9.17b0    true    uBlock0@raymondhill.net
Universal Search    1.0.12  true    universal-search@mozilla.com
Web Compat  1.0 true    webcompat@mozilla.org
Windscribe  0.1.43  true    @windscribeff
Beyond Australis    1.4.6   false   thefoxonlybetter@quicksaver
### Are there any errors showing in the developer console?

No.

**Comment by sivaraam** [comment]
I too noticed the same in Firefox Nightly 52.0a1 on Debian GNU/Linux. I haven't noticed any suggestions in the address from the day I enabled this using Test pilot.

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
