### ISSUE TITLE
Search site recommendations can be a bit biased.

### ISSUE THREAD

**Issue by moonmehta** [mozilla/universal-search#333]
Universal Search recommendations appears biased since it only looks at the patterns of keywords. For example (see attached image), searching for "linux "  (that's linux + "space") gives https://linuxmint.com/ as a recommendation.

![universal search](https://cloud.githubusercontent.com/assets/22585732/20646127/7f6900ee-b49a-11e6-9d81-012ce9dfad05.png)

Now there are other Linux distributions too, and even famous ones (like Ubuntu, Fedora, Arch, Debian, OpenSUSE, etc.). Recommending Linux Mint as a site for the search term linux can do a bias to people who might think that this is the best Linux or something, people who might not be aware or might not be tech-savvy.

I think, sticking to the Wikipedia page would be a good idea which appears on just searching "linux" without the space that follows.

### On what OS did you encounter this issue?
Ubuntu 16.10

### What version of Firefox are you using? 
Firefox 52 Developer Edition

### Please list all add-ons you have installed in Firefox
All the add-ons from Firefox Test Pilot, no more

### Are there any errors showing in the developer console? 
No

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
