### ISSUE TITLE
Check for recommendation images in the browser cache

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#75]
We should be able to get a pointer to the browser cache service, then check if the image URL is in the cache; if it's there, use it; if not, use the letterbox, and in the background, insert the image into the cache.

This will ensure that we never have to wait for network to display an image in the recommendation.

It looks like there's an (incompletely implemented?) new cache2 API (available as `Services.cache2`), and the old cache IDLs are marked as deprecated. I found some super rough docs on MDN [here](https://developer.mozilla.org/en-US/docs/Mozilla/HTTP_cache), but I don't see many examples of its use [in dxr](https://dxr.mozilla.org/mozilla-central/search?q=Services.cache2).

So, altogether, I'm sure we can somehow do this, and it'll help with performance quite a bit. I'm just not sure how to use the cache2 IDLs. They can be perused in [this folder](https://dxr.mozilla.org/mozilla-central/source/netwerk/cache2) in dxr.

**Comment by chuckharmston** [comment]
Notes from an IRC chat about this:
- Relying on browser caching is good, but normal loading techniques with proper headers will allow this.
- The correct solution to this is having an image proxy to do loading, resizing, and caching for us.
- That proxy should be containerized and served at the same hostname as the recommendation server, so we can take advantage of the H/2 request multiplexing we're already using.
