### ISSUE TITLE
Limit recommendations to specific markets

### ISSUE THREAD

**Issue by nchapman** [mozilla/universal-search#76]
Due to various contractual requirements, we should make sure we can limit recommendations to specific markets rather than only specific languages. There are previous examples of doing this for other search experiments so we should look into how those were done.

**Comment by chuckharmston** [comment]
Can we get more details on what the requirements specifically are, and where this has been tried before? I'm not exactly sure what this is asking.

**Comment by jaredhirsch** [comment]
@nchapman what about en-US? That's an American locale. Is that specific enough?

**Comment by jaredhirsch** [comment]
@lmorchard Should this requirement actually be something handled by the main test pilot add-on? If we want to restrict search add-on installs to country-specific locales, is there any way to filter the experiments view shown to a given user?

The best this add-on could do would be to let the user install it, then tell them that it won't work--seems like an awful user experience.

**Comment by jaredhirsch** [comment]
@nchapman Previous search experiments were probably telemetry experiments, which indeed [filter on locale](https://dxr.mozilla.org/mozilla-central/source/browser/experiments/docs/manifest.rst#192-203). My best guess is that this should be a bug on the test pilot repo.

**Comment by jaredhirsch** [comment]
This seems like an issue to address in the main test pilot app. Opened https://github.com/mozilla/testpilot/issues/468, closing this one.
