### ISSUE TITLE
Update docs to JSDoc style

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#77]
Our docs currently have a mix of inline and multi-line styles. Let's switch to [JSDoc](http://usejsdoc.org/index.html), which can auto-generate a documentation website for the project from the docs.

For this bug, we just want to update the format of the main docs. This should include:
- Constructor comments: move constructor docs to jsdoc style doc blocks above the constructor, and add the `@constructor` tag.
- Function comments: Some functions have high-level explanations at the top of the function body. Convert these to jsdoc style docs, and move them just above the function signature, but don't bother inserting tags for input parameters or the returned value.
- Skip inline comments: For this first pass, don't bother converting inline comments that are mixed in with code within function bodies.
- Don't worry about installing jsdoc, we'll do that in a separate bug. This is just about formatting.

**Comment by SuhaylTFaris** [comment]
I will work on this.

**Comment by jaredhirsch** [comment]
Hey @SuhaylTFaris, if you're still interested in working on this issue, let me know. I'm happy to help you get started.
