### ISSUE TITLE
Use separate highlight styles for different platforms

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#78]
_This might be a little too ambitious for a good first bug, so if you are a new contributor and are interested in taking this on, please ping me to get guidance before you start. IRC is best (my nick is _6a68), or leave a comment in this bug._

Right now, we style the recommendation [the same way](https://github.com/mozilla/universal-search/blob/master/chrome/skin/style.css) for all platforms. In general, this is fine, but it would be nice to have platform-specific highlight behavior when the recommendation row is selected.

Here's a sketch of the tasks required:
- Create individual files in the `chrome/skin/` directory for mac, windows, and linux.
- In each file, copy over the highlight style for each platform (see [this comment](https://github.com/mozilla/universal-search/pull/73#discussion_r55405801) for links to files). You want to take the `.autocomplete-richlistitem[selected=true]` rules, but apply them to the `#universal-search-recommendation` selector.
- Modify the [stylesheet loading code](https://github.com/mozilla/universal-search/blob/master/lib/universal-search.js#L82-L94) to add a check for the platform type, then load a second, platform-specific highlight stylesheet.
- You can get the platform type by checking the value of `Services.appinfo.OS`. The possible values of interest are `'Darwin'`, '`Linux'`, and `'WINNT'`. (It takes about 4 hops in MDN to track this info down, directly inserting the answer here to keep the bug manageable overall.)
- Once the changes are made, restart Firefox and see if the recommendation highlight matches the highlight of the other rows in the autocomplete dropdown. If it looks good, open a pull request. Don't worry about checking all three platforms; I can check that.

**Comment by kaganjd** [comment]
starting to dig into this one!
