### ISSUE TITLE
Recommendation image not showing up while highlighted.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#84]
![edd49a4e-e767-11e5-88fa-9bae2645a788](https://cloud.githubusercontent.com/assets/23885/13712419/b0212c8a-e780-11e5-8716-61e23aa6c186.png)

This is likely because it has z-index: -1, which is needed for its parent's inset box shadow to overlay it. 

Fix: when highlighted, we can set a normal z-index, unset the box shadow, and set a white background color on the image.

**Comment by jaredhirsch** [comment]
I'd prefer to just remove box shadow completely. It's just not that important in a short-lived interface.

**Comment by chuckharmston** [comment]
Without it, it looks pretty bad when the background of the icon returned is white.
