### ISSUE TITLE
Recommendation image hidden by highlight

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#86]
Seems like a CSS issue specific to the image, as the letterbox is unaffected.

Unhighlighted:

<img width="498" alt="screen shot 2016-03-14 at 2 02 49 pm" src="https://cloud.githubusercontent.com/assets/96396/13759879/88d34702-e9ed-11e5-9a54-61ff98025274.png">

Highlighted:

<img width="491" alt="screen shot 2016-03-14 at 2 02 54 pm" src="https://cloud.githubusercontent.com/assets/96396/13759883/8d918fd8-e9ed-11e5-9fe0-ecd2a3a84a35.png">

Highlighted letterbox:

<img width="496" alt="screen shot 2016-03-14 at 2 04 21 pm" src="https://cloud.githubusercontent.com/assets/96396/13759908/b18b4cf8-e9ed-11e5-8ac8-e348bc078f0b.png">

**Comment by chuckharmston** [comment]
Dupe: https://github.com/mozilla/universal-search/issues/84
