### ISSUE TITLE
Recommendation shouldn't be highlighted until user arrows down

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#96]
The default behavior highlights a row that corresponds to what would happen anyway if you hit Enter with the focus in the urlbar:

<img width="480" alt="screen shot 2016-03-21 at 8 48 32 am" src="https://cloud.githubusercontent.com/assets/96396/13924488/c599badc-ef41-11e5-92bc-2572d126e634.png">

When we steal focus for the recommendation, it seems like hitting Enter would take you to the recommendation URL, but you actually have to key down, then back up, to get the recommendation URL into the urlbar (or click on it).
1. user types 'f'
   <img width="399" alt="screen shot 2016-03-21 at 8 49 48 am" src="https://cloud.githubusercontent.com/assets/96396/13924510/e3358e9a-ef41-11e5-8acb-4ebd09590817.png">
2. user keys down
   <img width="432" alt="screen shot 2016-03-21 at 8 50 04 am" src="https://cloud.githubusercontent.com/assets/96396/13924540/f7994aac-ef41-11e5-8f5e-876c14347570.png">
3. user keys back up to the recommendation, now the URL is in the urlbar
   <img width="471" alt="screen shot 2016-03-21 at 8 50 08 am" src="https://cloud.githubusercontent.com/assets/96396/13924549/02e763e4-ef42-11e5-95bb-e4982d999499.png">

Maybe the better interaction would be to not highlight the recommendation until the user hits the down arrow for the first time?

**Comment by bryanbell** [comment]
We're not supposed to steal focus. We're supposed to have no focus on anything in the drop-down until the user hits the down cursor. 

<img width="1359" alt="urlbar" src="https://cloud.githubusercontent.com/assets/228979/13934468/a5065072-ef6f-11e5-9cc9-48a604e57a3a.png">

**Comment by jaredhirsch** [comment]
@bryanbell sounds good! I'll file a bug.

**Comment by jaredhirsch** [comment]
Oh wait, I'll just remove the '?' from the title of this bug

**Comment by jaredhirsch** [comment]
Agonizingly close. Just need to revert to the user's typed string when wrapping around from the bottom of the list to the urlbar.

https://github.com/6a68/universal-search/tree/96-adjust-default-highlight

**Comment by chuckharmston** [comment]
Moving back to @6a68; I accidentally stole it when I typo-ed a different issue's pull request.
