### ISSUE TITLE
Update recommendation layout to match new awesomebar styles

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#98]
I just found out that nightly is soon going to show results all on one line, Chrome-style (see image below).

We'll need to update our recommendation's layout to match, but not until the new design gets closer to release.

![image](https://cloud.githubusercontent.com/assets/96396/13964019/132c7756-f025-11e5-875e-502fd7175181.png)

**Comment by chuckharmston** [comment]
Awesome catch.

This should probably be automatic (if we can detect this somehow?) and override-able with a preference while it rides the trains.

**Comment by chuckharmston** [comment]
This landed last night: https://hg.mozilla.org/mozilla-central/rev/061165ac1ff9

Our popup works great:

![screen shot 2016-04-06 at 10 24 27 am](https://cloud.githubusercontent.com/assets/23885/14324694/171205b0-fbe3-11e5-88eb-49bf0120d8b6.png)

There are some new properties here that we should be able to use to figure out if the new UI is in place, such as [`_siteIcon`](https://hg.mozilla.org/mozilla-central/diff/061165ac1ff9/toolkit/content/widgets/autocomplete.xml#l1.164).

**Comment by jaredhirsch** [comment]
Cool, let's work on this once the patch stabilizes and reaches dev edition.

**Comment by jaredhirsch** [comment]
> This should probably be automatic (if we can detect this somehow?) and override-able with a preference while it rides the trains.

We can probably adjust the layout based on the Firefox version.

**Comment by chuckharmston** [comment]
This hit developer edition today.

**Comment by chuckharmston** [comment]
<img width="195" alt="screen shot 2016-04-30 at 10 16 33 pm" src="https://cloud.githubusercontent.com/assets/23885/14940048/53ec1d94-0f21-11e6-8e17-e957456a1234.png">

@bryanbell I think we'd want some unique iconography to align with the bookmark stars here, rather than a text label. A lightbulb, perhaps?

**Comment by chuckharmston** [comment]
Moving out of `In Progress` while we wait for this patch to settle more; there are some possible layout changes in the pipeline.

**Comment by shorlander** [comment]
There shouldn't be any more major layout changes to the updated results in Nightly.
